// debug_llm_html.js
//
// Returns the raw HTML generated by the LLM — no rendering, no painting.
// Use this to inspect what Qwen2.5 (or any model) actually produces before
// trying to render it.
//
// Usage:
//   curl -s -X POST http://localhost:9984/run \
//     --data-binary @src/examples/generative/debug_llm_html.js
//   # Returns the HTML as plain text in the response.
//
// To test a specific prompt, edit PROMPT below or pass it via query:
//   curl -s "http://localhost:9984/run?prompt=..." — not implemented here, just edit inline.

const PROMPT = "A responsive table with 3 columns: Name, Status, Amount. Include 5 realistic sample rows. Use a blue header.";
const MODEL   = "qwen2.5-coder:7b";
const BASE_URL = "http://localhost:11434";

async function run() {
  console.log("[debug] calling llmHTML, model:", MODEL);
  const html = await zxp.llmHTML({ model: MODEL, prompt: PROMPT, base_url: BASE_URL });
  console.log("[debug] LLM returned", html.length, "bytes");
  return html;  // returned as text/plain by the /run endpoint
}

run();
