// Invoice PDF Generator — SVG visual layer + real searchable PDF text
//
// The SVG template handles all decorative elements (header bar, accent stripe,
// table borders, totals box, footer). Real PDF text is laid on top so it stays
// searchable, selectable, and accessible in any PDF reader.

async function handlePdfGenerationRequest(data) {
  console.log("Generating invoice PDF...");

  // --- 1. Load resources ---
  const templateRes = await fetch("file://src/examples/test_invoice_template.svg");
  const svgText = await templateRes.text();
  console.log("SVG template loaded:", svgText.length, "chars");

  const logoRes = await fetch(data.logoUrl);
  const logoBlob = await logoRes.blob();
  console.log("Logo loaded:", logoBlob.size, "bytes");

  // Rasterize SVG background and decode logo
  const svgBlob = new Blob([svgText], { type: "image/svg+xml" });
  const bgBitmap = await createImageBitmap(svgBlob);
  console.log("SVG rasterized:", bgBitmap.width, "x", bgBitmap.height);

  const logoBitmap = await createImageBitmap(logoBlob);
  console.log("Logo decoded:", logoBitmap.width, "x", logoBitmap.height);

  // --- 2. Create PDF and draw background layer ---
  const pdf = new PDFDocument();
  pdf.addPage();

  // Draw the SVG background (fills the entire A4 page)
  pdf.drawImage(bgBitmap, 0, 0, 595, 842);

  // Draw logo in the header — circular clip like a profile avatar
  pdf.saveGraphicsState();
  pdf.arc(80, 60, 35, 0, 2 * Math.PI);  // circle centered on the 70x70 logo area
  pdf.clip();
  pdf.drawImage(logoBitmap, 45, 25, 70, 70);
  pdf.restoreGraphicsState();

  // --- 3. Header text (white on dark background) ---
  pdf.fillStyle = "#ffffff";
  pdf.setFont("Roboto", 28);
  pdf.fillText("INVOICE", 140, 65);

  pdf.setFont("Roboto", 11);
  pdf.fillText(data.company, 140, 85);
  pdf.fillText(data.companyEmail, 140, 100);

  // --- 4. Invoice details (right-aligned box) ---
  pdf.fillStyle = "#1e293b";
  pdf.setFont("Roboto", 10);
  pdf.fillText("Invoice #:", 365, 180);
  pdf.fillText("Date:", 365, 196);
  pdf.fillText("Due Date:", 365, 212);

  pdf.fillStyle = "#475569";
  pdf.fillText(data.invoiceNumber, 440, 180);
  pdf.fillText(data.date, 440, 196);
  pdf.fillText(data.dueDate, 440, 212);

  // --- 5. Bill To ---
  pdf.fillStyle = "#64748b";
  pdf.setFont("Roboto", 10);
  pdf.fillText("BILL TO", 50, 180);

  pdf.fillStyle = "#1e293b";
  pdf.setFont("Roboto", 12);
  pdf.fillText(data.customerName, 50, 200);

  pdf.fillStyle = "#475569";
  pdf.setFont("Roboto", 10);
  pdf.fillText(data.customerAddress, 50, 218);
  pdf.fillText(data.customerEmail, 50, 234);

  // --- 6. Items table ---
  // Table header
  pdf.fillStyle = "#64748b";
  pdf.setFont("Roboto", 10);
  pdf.fillText("Description", 55, 363);
  pdf.fillText("Qty", 360, 363);
  pdf.fillText("Price", 410, 363);
  pdf.fillText("Total", 490, 363);

  // Table rows
  pdf.fillStyle = "#1e293b";
  pdf.setFont("Roboto", 10);
  let rowY = 398;
  let subtotal = 0;

  for (const item of data.items) {
    const lineTotal = item.qty * item.price;
    subtotal += lineTotal;

    pdf.fillText(item.description, 55, rowY);
    pdf.fillText(String(item.qty), 368, rowY);
    pdf.fillText(`$${item.price.toFixed(2)}`, 410, rowY);
    pdf.fillText(`$${lineTotal.toFixed(2)}`, 490, rowY);
    rowY += 36;
  }

  // --- 7. Totals ---
  const tax = subtotal * data.taxRate;
  const total = subtotal + tax;

  pdf.fillStyle = "#475569";
  pdf.setFont("Roboto", 10);
  pdf.fillText("Subtotal:", 365, 540);
  pdf.fillText(`Tax (${(data.taxRate * 100).toFixed(0)}%):`, 365, 558);

  pdf.fillText(`$${subtotal.toFixed(2)}`, 480, 540);
  pdf.fillText(`$${tax.toFixed(2)}`, 480, 558);

  pdf.fillStyle = "#1e293b";
  pdf.setFont("Roboto", 14);
  pdf.fillText("Total:", 365, 582);
  pdf.fillText(`$${total.toFixed(2)}`, 472, 582);

  // --- 8. Footer ---
  pdf.fillStyle = "#94a3b8";
  pdf.setFont("Roboto", 9);
  const footerText = `Thank you for your business! — Generated by Zexplorer`;
  const footerM = pdf.measureText(footerText);
  const footerX = (595 - footerM.width) / 2;
  pdf.fillText(footerText, footerX, 820);

  console.log(`Invoice generated: ${data.invoiceNumber}`);
  return pdf.toArrayBuffer();
}

// Default test data
async function generateTestInvoice() {
  try {
    return await handlePdfGenerationRequest({
      company: "Zexplorer Labs",
      companyEmail: "billing@zexplorer.dev",
      logoUrl: "https://github.com/ndrean.png",
      invoiceNumber: "INV-2025-0042",
      date: "2025-02-15",
      dueDate: "2025-03-15",
      customerName: "Linus Torvalds",
      customerAddress: "1 Open Source Way, Portland OR",
      customerEmail: "torvalds@linux-foundation.org",
      taxRate: 0.2,
      items: [
        { description: "Headless DOM Engine — Annual License", qty: 1, price: 2400.0 },
        { description: "SVG Rasterization Add-on (ThorVG)", qty: 1, price: 800.0 },
        { description: "PDF Generation Module (LibHaru)", qty: 1, price: 600.0 },
      ],
    });
  } catch (e) {
    console.error("Invoice generation failed:", e);
    if (e && e.message) console.error("  message:", e.message);
    if (e && e.stack) console.error("  stack:", e.stack);
    throw e;
  }
}
