//! Bytecode Generator Tool
//!
//! Compiles a JavaScript source file to QuickJS bytecode and writes
//! a Zig source file containing the bytecode as a const array literal.
//! Used by the build system to embed precompiled JS into the binary.
//!
//! Usage:
//!   gen-bytecode <input.js> <output.zig> [--mode global|module]
//!
//! Default mode: global (correct for UMD/IIFE and plain scripts).
//! Use --mode module for ES module source (import/export syntax).

const std = @import("std");
const qjs = @cImport({
    @cInclude("quickjs.h");
});

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const args = try std.process.argsAlloc(allocator);
    defer std.process.argsFree(allocator, args);

    if (args.len < 3) {
        std.debug.print("Usage: {s} <input.js> <output.zig> [--mode global|module]\n", .{args[0]});
        std.process.exit(1);
    }

    const input_path = args[1];
    const output_path = args[2];

    // Parse optional --mode flag (default: global)
    var use_module = false;
    var i: usize = 3;
    while (i < args.len) : (i += 1) {
        if (std.mem.eql(u8, args[i], "--mode") and i + 1 < args.len) {
            i += 1;
            use_module = std.mem.eql(u8, args[i], "module");
        }
    }

    // Read source
    const source = std.fs.cwd().readFileAlloc(allocator, input_path, 10 * 1024 * 1024) catch |err| {
        std.debug.print("Error reading {s}: {}\n", .{ input_path, err });
        std.process.exit(1);
    };
    defer allocator.free(source);

    std.debug.print("Compiling {s} ({d} B, mode={s})\n", .{
        input_path, source.len, if (use_module) "module" else "global",
    });

    // QuickJS runtime + context
    const rt = qjs.JS_NewRuntime() orelse {
        std.debug.print("Failed to create QuickJS runtime\n", .{});
        std.process.exit(1);
    };
    defer qjs.JS_FreeRuntime(rt);

    const ctx = qjs.JS_NewContext(rt) orelse {
        std.debug.print("Failed to create QuickJS context\n", .{});
        std.process.exit(1);
    };
    defer qjs.JS_FreeContext(ctx);

    // Compile to bytecode only — do not execute
    const eval_type: c_int = if (use_module) qjs.JS_EVAL_TYPE_MODULE else qjs.JS_EVAL_TYPE_GLOBAL;
    const result = qjs.JS_Eval(ctx, source.ptr, source.len, input_path.ptr, eval_type | qjs.JS_EVAL_FLAG_COMPILE_ONLY);

    if (qjs.JS_IsException(result)) {
        const exc = qjs.JS_GetException(ctx);
        defer qjs.JS_FreeValue(ctx, exc);
        const str = qjs.JS_ToCString(ctx, exc);
        if (str != null) {
            std.debug.print("Compilation error in {s}:\n  {s}\n", .{ input_path, str });
            qjs.JS_FreeCString(ctx, str);
        }
        std.process.exit(1);
    }
    defer qjs.JS_FreeValue(ctx, result);

    // Serialize bytecode (strip source text — not needed at runtime)
    var bc_size: usize = undefined;
    const bc_ptr = qjs.JS_WriteObject(ctx, &bc_size, result, qjs.JS_WRITE_OBJ_BYTECODE | qjs.JS_WRITE_OBJ_STRIP_SOURCE);
    if (bc_ptr == null) {
        std.debug.print("Failed to serialize bytecode for {s}\n", .{input_path});
        std.process.exit(1);
    }
    defer qjs.js_free(ctx, bc_ptr);

    const bytecode = bc_ptr[0..bc_size];

    // Build Zig source file in memory, then write atomically.
    var out: std.Io.Writer.Allocating = .init(allocator);
    defer out.deinit();

    try out.writer.print(
        \\// Auto-generated by gen_bytecode — do not edit.
        \\// Source: {s}
        \\pub const data: []const u8 = &[_]u8{{
        \\
    , .{input_path});

    // 16 bytes per line for compact but readable output
    var byte_i: usize = 0;
    while (byte_i < bytecode.len) {
        try out.writer.writeAll("    ");
        const end = @min(byte_i + 16, bytecode.len);
        for (bytecode[byte_i..end]) |byte| {
            try out.writer.print("0x{x:0>2},", .{byte});
        }
        try out.writer.writeByte('\n');
        byte_i = end;
    }

    try out.writer.writeAll("};\n");

    const content = try out.toOwnedSlice();
    defer allocator.free(content);
    std.fs.cwd().writeFile(.{ .sub_path = output_path, .data = content }) catch |err| {
        std.debug.print("Error writing {s}: {}\n", .{ output_path, err });
        std.process.exit(1);
    };

    std.debug.print("  → {s} ({d} B bytecode, {d:.1}% of source)\n", .{
        output_path,
        bc_size,
        @as(f64, @floatFromInt(bc_size)) / @as(f64, @floatFromInt(source.len)) * 100.0,
    });
}
