//! Build-time async binding generator
//! Generates async bindings using auto_bridge pattern
//!
//! Usage: zig run tools/gen_async_bindings.zig -- src/async_bindings_generated.zig

const std = @import("std");

/// Specification for an async binding (using auto_bridge)
const AsyncBindingSpec = struct {
    name: []const u8, // JavaScript function name
    payload_type: []const u8, // e.g., "Worker.FetchPayload"
    worker_func: []const u8, // e.g., "Worker.workerFetch"
    arg_count: usize, // Number of JS arguments
    result_type: ?[]const u8 = null, // Optional: for bindAsyncJson (e.g., "FetchResult")
};

/// Async worker bindings (using auto_bridge)
const async_bindings = [_]AsyncBindingSpec{
    // .{
    //     .name = "fetch",
    //     .payload_type = "workers.FetchPayload",
    //     .worker_func = "workers.workerFetch",
    //     .arg_count = 1,
    //     .result_type = "workers.FetchResult",
    // },
    .{
        .name = "readFile",
        .payload_type = "workers.ReadFilePayload",
        .worker_func = "workers.workerReadFile",
        .arg_count = 1,
    },
    // .{
    //     .name = "simulateWork",
    //     .payload_type = "workers.SimulateWorkPayload",
    //     .worker_func = "workers.workerSimulateAsync",
    //     .arg_count = 1,
    // },
    // Add more async bindings here as needed
};

pub fn main() !void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    const args = try std.process.argsAlloc(allocator);
    if (args.len < 2) {
        std.debug.print("Usage: {s} <output_file>\n", .{args[0]});
        return;
    }

    const output_file_path = args[1];

    // Build output in memory
    // var output: std.ArrayList(u8) = .empty;
    // defer output.deinit(allocator);
    // const writer = output.writer(allocator);

    var aw = std.Io.Writer.Allocating.init(allocator);
    defer aw.deinit();
    const stdout = &aw.writer;

    // Generate file header
    try stdout.writeAll(
        \\// THIS FILE IS AUTO-GENERATED BY tools/gen_async_bindings.zig
        \\// DO NOT EDIT MANUALLY
        \\
        \\const AutoBridge = @import("auto_bridge.zig");
        \\const AsyncBridge = @import("async_bridge.zig");
        \\const workers = @import("workers.zig");
        \\const zqjs = @import("wrapper.zig");
        \\
        \\
    );

    // Generate bindings
    try stdout.writeAll("// Auto-generated async bindings\n");
    for (async_bindings) |binding| {
        if (binding.result_type) |result_type| {
            // Use bindAsyncJson with AutoBridge.genParser for structured return types
            try stdout.print(
                \\/// {s}() -> Promise<object>
                \\/// Auto-generated async binding (JSON)
                \\pub const js_{s} = AsyncBridge.bindAsyncJson(
                \\    {s},
                \\    {s},
                \\    AutoBridge.genParser({s}),
                \\    {s},
                \\);
                \\
                \\
            ,
                .{
                    binding.name,
                    binding.name,
                    binding.payload_type,
                    result_type,
                    binding.payload_type,
                    binding.worker_func,
                },
            );
        } else {
            // Use bindAsyncAuto for string return types
            try stdout.print(
                \\/// {s}() -> Promise<string>
                \\/// Auto-generated async binding
                \\pub const js_{s} = AutoBridge.bindAsyncAuto(
                \\    {s},
                \\    {s},
                \\);
                \\
                \\
            ,
                .{
                    binding.name,
                    binding.name,
                    binding.payload_type,
                    binding.worker_func,
                },
            );
        }
    }

    // Generate installer function
    try stdout.writeAll(
        \\
        \\/// Install Async Worker bindings
        \\pub fn installAllBindings(ctx: zqjs.Context, global: zqjs.Value) !void {
        \\    // Async worker APIs
        \\
    );

    for (async_bindings) |binding| {
        try stdout.print(
            \\    const {s}_fn = ctx.newCFunction(js_{s}, "{s}", {d});
            \\    _ = try ctx.setPropertyStr(global, "{s}", {s}_fn);
            \\
        ,
            .{
                binding.name,
                binding.name,
                binding.name,
                binding.arg_count,
                binding.name,
                binding.name,
            },
        );
    }

    try stdout.writeAll("}\n");

    // Write to file
    const file = try std.fs.cwd().createFile(output_file_path, .{});
    defer file.close();
    try file.writeAll(aw.writer.buffer[0..aw.writer.end]);

    std.debug.print("Generated {d} async bindings to {s}\n", .{
        async_bindings.len,
        output_file_path,
    });
}
