//! Build-time QuickJS binding generator
//! Generates type-safe wrappers using wrapper.zig types consistently
//! Use RuntimeContext for isolation.
//!
//! Usage:
//! ```sh
//! zig run tools/gen_bindings.zig -- src/bindings_generated.zig
//! ```

const std = @import("std");

pub const BindingKind = enum {
    static,
    method,
    property,
    boolean_attribute,
    string_attribute,
};

pub const BindingSpec = struct {
    name: []const u8,
    kind: BindingKind, // static = on document, method = on prototype
    attr_name: ?[]const u8 = null, // eg 'class'

    zig_func_name: []const u8 = "",
    args: []const ArgType = &.{},
    return_type: ReturnType = .void_type,

    getter: []const u8 = "", // e.g. "z.innerHTML"
    setter: []const u8 = "", // e.g. "z.setInnerHTML"
    prop_type: ReturnType = .void_type, // Type of the property (e.g. .string)
    prop_this: ArgType = .this_element, // What 'this' maps to (.this_element or .this_node)
};

pub const ArgType = union(enum) {
    allocator, // Uses rc.allocator
    context, // <--- Passes 'ctx' to Zig function
    callback, // <-- passes raw JS_Value
    dom_bridge,

    // SOURCES
    this_parser,
    this_element, // *HTMLElement from 'this'
    this_node, // *DomNode from 'this'
    this_document, // *HTMLDocument from 'this'
    element, // *HTMLElement from argv (passed as argument argv[i])
    node, // *DomNode from argv (passed as argument argv[i])
    document, // *HTMLDocument from global
    document_root, // *DomNode (root of document) from global

    // Primitives
    string, // []const u8
    int32, // i32
    uint32, // u32
    boolean, // bool
};

const ReturnType = union(enum) {
    void_type, // Returns void (no error check)
    void_with_error, // Returns !void (generates 'catch return w.EXCEPTION')
    element, // *HTMLElement
    optional_element, // ?*HTMLElement
    node, // *DomNode
    optional_node, // ?*DomNode
    document, // *HTMLDocument (No error)
    owned_document,

    string, // []const u8 (allocated, will be freed with allocator from args)
    optional_string, // ?[]const u8
    int32,
    uint32,
    boolean,

    // Special cases
    error_string, // ![]const u8
    error_document, // !*HTMLDocument
    error_owned_document,
};

// Define the bindings to generate
const bindings = @import("bindings.zig").bindings;

pub fn main() !void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    const args = try std.process.argsAlloc(allocator);
    if (args.len < 2) {
        std.debug.print("Usage: {s} <output_file>\n", .{args[0]});
        return;
    }

    const output_file_path = args[1];

    var aw = std.Io.Writer.Allocating.init(allocator);
    defer aw.deinit();
    const writer = &aw.writer;

    try writer.writeAll(
        \\// THIS FILE IS AUTO-GENERATED BY tools/gen_bindings.zig
        \\// DO NOT EDIT MANUALLY
        \\
        \\const std = @import("std");
        \\const z = @import("root.zig");
        \\const w = @import("wrapper.zig");
        \\const qjs = z.qjs;
        \\const DOMBridge = @import("dom_bridge.zig").DOMBridge;
        \\const RuntimeContext = @import("runtime_context.zig").RuntimeContext;
        \\
        \\
    );

    for (bindings) |binding| {
        if (binding.kind == .property) {
            try genGetter(writer, binding);
            if (binding.setter.len > 0) {
                try genSetter(writer, binding);
            }
        } else {
            try genFunction(writer, binding);
        }
    }

    // ============================================================
    // GENERATE INSTALLERS
    // ============================================================

    // 2. DOCUMENT Bindings (Static methods like createElement: doc_obj -> proto
    try writer.writeAll("\npub fn installDocumentBindings(ctx: ?*qjs.JSContext, proto: qjs.JSValue) void {\n");
    for (bindings) |binding| {
        if (binding.kind == .static or binding.prop_this == .this_document) {
            if (binding.kind == .property) {
                try genInstallerLine(writer, binding);
            } else {
                try writer.print(
                    "    _ = qjs.JS_SetPropertyStr(ctx, proto, \"{s}\", qjs.JS_NewCFunction(ctx, js_{s}, \"{s}\", {d}));\n",
                    .{ binding.name, binding.name, binding.name, countJsArgs(binding.args) },
                );
            }
        }
    }
    try writer.writeAll("}\n");

    // 3. NODE Prototype Bindings (appendChild, parentNode, etc.)
    try writer.writeAll("\npub fn installNodeBindings(ctx: ?*qjs.JSContext, proto: qjs.JSValue) void {\n");
    for (bindings) |binding| {
        //  Belongs to Node if 'this' is defined as .this_node
        const is_node_method = switch (binding.prop_this) {
            .this_node => true,
            else => if (binding.args.len > 0 and binding.args[0] == .this_node) true else false,
        };

        if (binding.kind != .static and is_node_method) {
            try genInstallerLine(writer, binding);
        }
    }
    try writer.writeAll("}\n");

    // 4. ELEMENT Prototype Bindings (innerHTML, setAttribute, etc.)
    try writer.writeAll("\npub fn installElementBindings(ctx: ?*qjs.JSContext, proto: qjs.JSValue) void {\n");
    for (bindings) |binding| {
        // If it's not 'static' and not a Node method, it's an Element method
        const is_node_method = switch (binding.prop_this) {
            .this_node => true,
            else => if (binding.args.len > 0 and binding.args[0] == .this_node) true else false,
        };

        if (binding.kind != .static and !is_node_method and binding.prop_this != .this_document and binding.prop_this != .this_parser) {
            try genInstallerLine(writer, binding);
        }
    }
    try writer.writeAll("}\n");

    // 5. DOMPARSER Prototype Bindings
    try writer.writeAll("\npub fn installDOMParserBindings(ctx: ?*qjs.JSContext, proto: qjs.JSValue) void {\n");
    for (bindings) |binding| {
        if (binding.prop_this == .this_parser) {
            try genInstallerLine(writer, binding);
        }
    }
    try writer.writeAll("}\n");

    // Write accumulated output to file
    const file = try std.fs.cwd().createFile(output_file_path, .{});
    defer file.close();
    try file.writeAll(aw.writer.buffer[0..aw.writer.end]);
}

fn genGetter(writer: anytype, func: BindingSpec) !void {
    try writer.print(
        \\
        \\// Property Getter for {s}
        \\pub fn js_get_{s}(
        \\    ctx_ptr: ?*qjs.JSContext,
        \\    this_val: qjs.JSValue,
        \\    argc: c_int,
        \\    argv: [*c]qjs.JSValue,
        \\) callconv(.c) qjs.JSValue {{
        \\    _ = argc; _ = argv;
        \\    const ctx = w.Context{{ .ptr = ctx_ptr }};
        \\    const rc = RuntimeContext.get(ctx);
        \\
    , .{ func.name, func.name });

    // 1. Unwrap 'this'
    // ensure we use the right cast type
    const cast_type = if (func.prop_this == .this_element) "*z.HTMLElement" else "*z.DomNode";

    // Check if we need polymorphic unwrapping (Node) or strict checking (Element)
    switch (func.prop_this) {
        .this_node => {
            try writer.writeAll(
                \\    const arg0_opt = DOMBridge.unwrapNode(ctx, this_val);
                \\    if (arg0_opt == null) return w.EXCEPTION; 
                \\    const this_arg = arg0_opt.?;
                \\
            );
        },
        .this_document => {
            // Check BOTH Document AND OwnedDocument
            try writer.writeAll(
                \\    const this_arg: *z.HTMLDocument = blk: {
                \\        if (qjs.JS_GetOpaque(this_val, rc.classes.document)) |ptr| break :blk @ptrCast(@alignCast(ptr));
                \\        if (qjs.JS_GetOpaque(this_val, rc.classes.owned_document)) |ptr| break :blk @ptrCast(@alignCast(ptr));
                \\        return ctx.throwTypeError("Method called on object that is not a Document (Class ID mismatch)");
                // \\        return w.EXCEPTION;
                \\    };
                \\
            );
        },
        .this_element => {
            try writer.writeAll(
                \\    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
                \\    if (ptr == null) return ctx.throwTypeError("Object is not an HTMLElement");
                \\    const this_arg: *z.HTMLElement = @ptrCast(@alignCast(ptr));
                \\
            );
        },
        else => {
            try writer.print(
                \\    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.dom_node);
                \\    if (ptr == null) return w.EXCEPTION;
                \\    const this_arg: {s} = @ptrCast(@alignCast(ptr));
                \\
            , .{cast_type});
        },
    }

    // 2. Call Zig Getter
    //  !! If returning string/error_string, we assume the Zig func needs (allocator, node).
    if (func.prop_type == .error_string or func.prop_type == .string) {
        try writer.print("    const result = {s}(rc.allocator, this_arg)", .{func.getter});
    } else {
        try writer.print("    const result = {s}(this_arg)", .{func.getter});
    }

    // 3. Handle Result & Return
    if (func.prop_type == .error_string) {
        try writer.writeAll(" catch return w.EXCEPTION;\n");
        try writer.writeAll("    defer rc.allocator.free(result);\n");
        try writer.writeAll("    return ctx.newString(result);\n");
    } else if (func.prop_type == .string) {
        try writer.writeAll(";\n");
        try writer.writeAll("    defer rc.allocator.free(result);\n");
        try writer.writeAll("    return ctx.newString(result);\n");
    } else if (func.prop_type == .boolean) {
        try writer.writeAll(";\n    return ctx.newBool(result);\n");
    } else if (func.prop_type == .optional_element) {
        try writer.writeAll(";\n    if (result) |elem| { return DOMBridge.wrapElement(ctx, elem) catch w.EXCEPTION; } else { return w.NULL; }\n");
    } else {
        try writer.writeAll(";\n    return w.UNDEFINED;\n");
    }

    try writer.writeAll("}\n");
}

fn genSetter(writer: anytype, func: BindingSpec) !void {
    try writer.print(
        \\
        \\// Property Setter for {s}
        \\pub fn js_set_{s}(
        \\    ctx_ptr: ?*qjs.JSContext,
        \\    this_val: qjs.JSValue,
        \\    argc: c_int,
        \\    argv: [*c]qjs.JSValue,
        \\) callconv(.c) qjs.JSValue {{
        \\    _ = argc;
        \\    const ctx = w.Context{{ .ptr = ctx_ptr }};
        \\    const rc = RuntimeContext.get(ctx);
        \\
    , .{ func.name, func.name });

    // 1. Unwrap 'this'
    const cast_type = if (func.prop_this == .this_element) "*z.HTMLElement" else "*z.DomNode";

    switch (func.prop_this) {
        .this_node => {
            try writer.writeAll(
                \\    _ = rc;
                \\    const arg0_opt = DOMBridge.unwrapNode(ctx, this_val);
                \\    if (arg0_opt == null) return w.EXCEPTION; 
                \\    const this_arg = arg0_opt.?;
                \\
            );
        },
        .this_document => {
            // Check BOTH Document AND OwnedDocument
            try writer.writeAll(
                \\    const this_arg: *z.HTMLDocument = blk: {
                \\        if (qjs.JS_GetOpaque(this_val, rc.classes.document)) |ptr| break :blk @ptrCast(@alignCast(ptr));
                \\        if (qjs.JS_GetOpaque(this_val, rc.classes.owned_document)) |ptr| break :blk @ptrCast(@alignCast(ptr));
                // \\        return w.EXCEPTION;
                \\        return ctx.throwTypeError("Method called on object that is not a Document (Class ID mismatch)");
                \\    };
                \\
            );
        },
        .this_element => {
            // Use rc.classes.html_element
            try writer.writeAll(
                \\    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
                \\    if (ptr == null) return w.EXCEPTION; 
                \\    const this_arg: *z.HTMLElement = @ptrCast(@alignCast(ptr));
                \\
            );
        },
        else => {
            try writer.print(
                \\    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.dom_node);
                \\    if (ptr == null) return w.EXCEPTION;
                \\    const this_arg: {s} = @ptrCast(@alignCast(ptr));
                \\
            , .{cast_type});
        },
    }
    // 2. Extract Value (from argv[0]) and Call Zig
    if (func.prop_type == .error_string or func.prop_type == .string) {
        try writer.writeAll(
            \\    const val = argv[0];
            \\    const val_str = ctx.toZString(val) catch return w.EXCEPTION;
            \\    defer ctx.freeZString(val_str);
            \\
        );
        // Setters usually don't take allocators (Lexbor handles internal memory)
        try writer.print("    {s}(this_arg, val_str) catch return w.EXCEPTION;\n", .{func.setter});
    } else if (func.prop_type == .boolean) {
        try writer.writeAll("    const val_bool = qjs.JS_ToBool(ctx_ptr, argv[0]) != 0;\n");
        try writer.print("    {s}(this_arg, val_bool);\n", .{func.setter});
    }

    try writer.writeAll("    return w.UNDEFINED;\n}\n");
}

fn genInstallerLine(writer: anytype, binding: BindingSpec) !void {
    if (binding.kind == .method) {
        try writer.print("    _ = qjs.JS_SetPropertyStr(ctx, proto, \"{s}\", qjs.JS_NewCFunction(ctx, js_{s}, \"{s}\", {d}));\n", .{ binding.name, binding.name, binding.name, countJsArgs(binding.args) });
    } else {
        // Properties
        try writer.print(
            \\    {{
            \\        const atom = qjs.JS_NewAtom(ctx, "{s}");
            \\        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_{s}, "get_{s}", 0, qjs.JS_CFUNC_generic, 0);
            \\
        , .{ binding.name, binding.name, binding.name });

        if (binding.setter.len > 0) {
            try writer.print(
                \\        const set_fn = qjs.JS_NewCFunction2(ctx, js_set_{s}, "set_{s}", 1, qjs.JS_CFUNC_generic, 0);
                \\
            , .{ binding.name, binding.name });
        } else {
            try writer.writeAll("        const set_fn = w.UNDEFINED;\n");
        }

        try writer.writeAll(
            \\        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
            \\        qjs.JS_FreeAtom(ctx, atom);
            \\    }
            \\
        );
    }
}

fn needsRc(func: BindingSpec) bool {
    // Check Return Type
    switch (func.return_type) {
        .document, .error_document, .error_owned_document, .owned_document => return true, // Needs rc.classes.dom_node
        else => {},
    }

    // Check Arguments
    for (func.args) |arg| {
        switch (arg) {
            .dom_bridge, // Uses rc.dom_bridge
            .allocator, // Uses rc.allocator
            .this_element, // Uses rc.classes.dom_node
            .document, // Uses rc.classes.dom_node
            .document_root, // Uses rc.classes.dom_node
            .element, // Uses rc.classes.dom_node
            .this_parser, // Uses rc.classes.dom_parser
            .this_document,
            => return true,
            else => {},
        }
    }
    return false;
}

fn countJsArgs(args: []const ArgType) usize {
    var count: usize = 0;
    for (args) |arg| {
        switch (arg) {
            .string, .int32, .uint32, .boolean, .element, .node => count += 1,
            else => {},
        }
    }
    return count;
}

fn genFunction(writer: *std.Io.Writer, func: BindingSpec) !void {

    // Handle property bindings
    // 1. HANDLE PROPERTIES
    if (func.kind == .property) {

        // --- GENERATE GETTER ------------------------------------------------
        try writer.print(
            \\
            \\// Property Getter for {s}
            \\pub fn js_get_{s}(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {{
            \\    _ = argc; _ = argv;
            \\    const ctx = w.Context{{ .ptr = ctx_ptr }};
            \\    const rc = RuntimeContext.get(ctx);
            \\
        , .{ func.name, func.name });

        // 1. Extract 'this'
        const cast_type = if (func.prop_this == .this_element) "*z.HTMLElement" else "*z.DomNode";
        try writer.print(
            \\    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.dom_node);
            \\    if (ptr == null) return w.EXCEPTION;
            \\    const this_arg: {s} = @ptrCast(@alignCast(ptr));
            \\
        , .{cast_type});

        // 2. Call Zig Getter
        if (func.prop_type == .error_string or func.prop_type == .string) {
            try writer.print("    const result = {s}(rc.allocator, this_arg)", .{func.getter});
        } else {
            try writer.print("    const result = {s}(this_arg)", .{func.getter});
        }

        // 3. Catch & Marshal
        if (func.prop_type == .error_string) {
            try writer.writeAll(" catch return w.EXCEPTION;\n");
            try writer.writeAll("    defer rc.allocator.free(result);\n");
            try writer.writeAll("    return ctx.newString(result);\n");
        } else if (func.prop_type == .string) {
            try writer.writeAll(";\n");
            try writer.writeAll("    defer rc.allocator.free(result);\n");
            try writer.writeAll("    return ctx.newString(result);\n");
        } else if (func.prop_type == .boolean) {
            try writer.writeAll(";\n    return ctx.newBool(result);\n");
        } else {
            try writer.writeAll(";\n    return w.UNDEFINED;\n");
        }
        try writer.writeAll("}\n");

        // --- GENERATE SETTER ------------------------------------------------
        try writer.print(
            \\
            \\// Property Setter for {s}
            \\pub fn js_set_{s}(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {{
            \\    _ = argc;
            \\    const ctx = w.Context{{ .ptr = ctx_ptr }};
            \\    const rc = RuntimeContext.get(ctx);
            \\
        , .{ func.name, func.name });

        // 1. Extract 'this'
        try writer.print(
            \\    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.dom_node);
            \\    if (ptr == null) return w.EXCEPTION;
            \\    const this_arg: {s} = @ptrCast(@alignCast(ptr));
            \\
        , .{cast_type});

        // 2. Extract Value (From argv[0]!)
        if (func.prop_type == .error_string or func.prop_type == .string) {
            try writer.writeAll(
                \\    const val = argv[0];
                \\    const val_str = ctx.toZString(val) catch return w.EXCEPTION;
                \\    defer ctx.freeZString(val_str);
                \\
            );
            try writer.print("    {s}(this_arg, val_str) catch return w.EXCEPTION;\n", .{func.setter});
        } else if (func.prop_type == .boolean) {
            try writer.writeAll("    const val_bool = qjs.JS_ToBool(ctx_ptr, argv[0]) != 0;\n");
            try writer.print("    {s}(this_arg, val_bool);\n", .{func.setter});
        }

        try writer.writeAll("    return w.UNDEFINED;\n}\n");
        return; // DONE
    }

    // 1. HANDLE BOOLEAN ATTRIBUTES (e.g. .disabled, .hidden)
    if (func.kind == .boolean_attribute) {

        // --- GENERATE GETTER (z.hasAttribute) ---
        try writer.print(
            \\
            \\// Boolean Getter for {s}
            \\pub fn js_get_{s}(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {{
            \\    _ = argc; _ = argv;
            \\    const ctx = w.Context{{ .ptr = ctx_ptr }};
            \\    const rc = RuntimeContext.get(ctx);
            \\
            \\    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
            \\    if (ptr == null) return w.EXCEPTION;
            \\    const this_arg: *z.HTMLElement = @ptrCast(@alignCast(ptr));
            \\
            \\    const is_present = z.hasAttribute(this_arg, "{s}");
            \\    return ctx.newBool(is_present);
            \\}}
            \\
        , .{ func.name, func.name, func.name }); // Use func.name as the attribute name

        // --- GENERATE SETTER (z.setAttribute / z.removeAttribute) ---
        try writer.print(
            \\
            \\// Boolean Setter for {s}
            \\pub fn js_set_{s}(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {{
            \\    _ = argc;
            \\    const ctx = w.Context{{ .ptr = ctx_ptr }};
            \\    const rc = RuntimeContext.get(ctx);
            \\
            \\    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
            \\    if (ptr == null) return w.EXCEPTION;
            \\    const this_arg: *z.HTMLElement = @ptrCast(@alignCast(ptr));
            \\
            \\    // Convert JS value to boolean
            \\    const val = qjs.JS_ToBool(ctx_ptr, argv[0]) != 0;
            \\
            \\    if (val) {{
            \\        z.setAttribute(this_arg, "{s}", "") catch return w.EXCEPTION;
            \\    }} else {{
            \\        z.removeAttribute(this_arg, "{s}") catch return w.EXCEPTION;
            \\    }}
            \\    return w.UNDEFINED;
            \\}}
            \\
        , .{ func.name, func.name, func.name, func.name });

        return; // Done
    }

    // 2. HANDLE STRING ATTRIBUTES (id, title, className, etc.)
    if (func.kind == .string_attribute) {
        // Determine the HTML attribute name (default to JS name if null)
        const attr = if (func.attr_name) |n| n else func.name;

        // --- GENERATE GETTER ---
        try writer.print(
            \\
            \\// Reflected String Getter for {s} -> {s}
            \\pub fn js_get_{s}(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {{
            \\    _ = argc; _ = argv;
            \\    const ctx = w.Context{{ .ptr = ctx_ptr }};
            \\    const rc = RuntimeContext.get(ctx);
            \\
            \\    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
            \\    if (ptr == null) return w.EXCEPTION;
            \\    const this_arg: *z.HTMLElement = @ptrCast(@alignCast(ptr));
            \\
            \\    // Call getAttribute (returns allocated !?[]u8)
            \\    const val_opt = z.getAttribute(rc.allocator, this_arg, "{s}") catch return w.EXCEPTION;
            \\    if (val_opt) |val| {{
            \\        defer rc.allocator.free(val);
            \\        return ctx.newString(val);
            \\    }}
            \\    // Reflected attributes usually return empty string if missing (not null)
            \\    return ctx.newString("");
            \\}}
            \\
        , .{ func.name, attr, func.name, attr });

        // --- GENERATE SETTER ---
        try writer.print(
            \\
            \\// Reflected String Setter for {s} -> {s}
            \\pub fn js_set_{s}(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {{
            \\    _ = argc;
            \\    const ctx = w.Context{{ .ptr = ctx_ptr }};
            \\    const rc = RuntimeContext.get(ctx);
            \\
            \\    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
            \\    if (ptr == null) return w.EXCEPTION;
            \\    const this_arg: *z.HTMLElement = @ptrCast(@alignCast(ptr));
            \\
            \\    const val_str = ctx.toZString(argv[0]) catch return w.EXCEPTION;
            \\    defer ctx.freeZString(val_str);
            \\
            \\    z.setAttribute(this_arg, "{s}", val_str) catch return w.EXCEPTION;
            \\    return w.UNDEFINED;
            \\}}
            \\
        , .{ func.name, attr, func.name, attr });

        return;
    }

    // --- GENERATE FUNCTION BINDING ---
    try writer.print(
        \\
        \\/// Generated wrapper for {s}
        \\pub fn js_{s}(
        \\    ctx_ptr: ?*qjs.JSContext,
        \\    this_val: qjs.JSValue,
        \\    argc: c_int,
        \\    argv: [*c]qjs.JSValue,
        \\) callconv(.c) qjs.JSValue {{
        \\    const ctx = w.Context{{ .ptr = ctx_ptr }};
        \\
    , .{ func.zig_func_name, func.name });

    if (needsRc(func)) {
        try writer.writeAll("    const rc = RuntimeContext.get(ctx);\n");
    }

    // 1. ARGUMENT CHECKS
    const js_arg_count = countJsArgs(func.args);
    if (js_arg_count > 0) {
        try writer.print("    if (argc < {d}) return w.EXCEPTION;\n", .{js_arg_count});
    }

    // 2. UNUSED VARS SUPPRESSION
    if (js_arg_count == 0) {
        try writer.writeAll("    _ = argc; _ = argv;\n");
    }
    var uses_this = false;
    var uses_ctx = false;
    for (func.args) |arg| {
        switch (arg) {
            .this_element, .this_node, .this_parser, .this_document => uses_this = true,
            .string, .document, .document_root, .element, .node => uses_ctx = true,
            // Allocator removed from uses_ctx because we use rc.allocator now

            else => {},
        }
    }
    if (!uses_this) {
        try writer.writeAll("    _ = this_val;\n");
    }

    // Suppress ctx usage check if nothing uses it
    const return_needs_ctx = (func.return_type == .element or func.return_type == .node or
        func.return_type == .optional_element or func.return_type == .optional_node or
        func.return_type == .string or func.return_type == .error_string or func.return_type == .optional_string or
        func.return_type == .int32 or func.return_type == .uint32 or func.return_type == .boolean);

    // Note: 'rc' uses ctx, so ctx is almost always used now.
    // suppression logic commented, just in case, but updated.
    if (!uses_ctx and !return_needs_ctx) {
        // try writer.writeAll("    _ = ctx;\n"); // Context is used for RuntimeContext.get(ctx) above
    }

    // 3. EXTRACT ARGUMENTS
    var js_arg_idx: usize = 0;
    var allocator_idx: ?usize = null;

    for (func.args, 0..) |arg, i| {
        switch (arg) {
            .dom_bridge => {
                // rc is already defined at the top of the generated function
                try writer.print("    const arg{d}: *DOMBridge = @ptrCast(@alignCast(rc.dom_bridge.?));\n", .{i});
            },
            .context => {
                try writer.print("    const arg{d} = ctx;\n", .{i});
                // No js_arg_idx increment (internal arg)
            },
            .callback => {
                try writer.print("    const arg{d} = argv[{d}];\n", .{ i, js_arg_idx });
                js_arg_idx += 1;
            },
            .allocator => {
                // Use rc.allocator (Thread-local allocator)
                try writer.print("    const arg{d} = rc.allocator;\n", .{i});
                allocator_idx = i;
            },
            .this_element => {
                // Use rc.classes.dom_node
                try writer.print(
                    \\    const elem_ptr{d} = qjs.JS_GetOpaque(this_val, rc.classes.dom_node);
                    \\    if (elem_ptr{d} == null) return w.EXCEPTION;
                    \\    const arg{d}: *z.HTMLElement = @ptrCast(@alignCast(elem_ptr{d}));
                    \\
                , .{ i, i, i, i });
            },
            .this_node => {
                try writer.print(
                    \\    const arg{d}_opt = DOMBridge.unwrapNode(ctx, this_val);
                    \\    if (arg{d}_opt == null) return ctx.throwTypeError("'this' is not a Node (or unwrap failed)");
                    \\    const arg{d} = arg{d}_opt.?;
                    \\
                , .{ i, i, i, i });
            },
            .document => {
                // Use rc.classes.dom_node
                try writer.print(
                    \\    const global{d} = ctx.getGlobalObject();
                    \\    defer ctx.freeValue(global{d});
                    \\    const doc_obj{d} = ctx.getPropertyStr(global{d}, "document");
                    \\    defer ctx.freeValue(doc_obj{d});
                    \\    const native_doc{d} = ctx.getPropertyStr(doc_obj{d}, "_native_doc");
                    \\    defer ctx.freeValue(native_doc{d});
                    \\    const doc_ptr{d} = qjs.JS_GetOpaque(native_doc{d}, rc.classes.document);
                    \\    if (doc_ptr{d} == null) return w.EXCEPTION;
                    \\    const arg{d}: *z.HTMLDocument = @ptrCast(@alignCast(doc_ptr{d}));
                    \\
                , .{ i, i, i, i, i, i, i, i, i, i, i, i, i });
            },
            .document_root => {
                // Use rc.classes.dom_node
                try writer.print(
                    \\    const global{d} = ctx.getGlobalObject();
                    \\    defer ctx.freeValue(global{d});
                    \\    const doc_obj{d} = ctx.getPropertyStr(global{d}, "document");
                    \\    defer ctx.freeValue(doc_obj{d});
                    \\    const native_doc{d} = ctx.getPropertyStr(doc_obj{d}, "_native_doc");
                    \\    defer ctx.freeValue(native_doc{d});
                    \\    const doc_ptr{d} = qjs.JS_GetOpaque(native_doc{d}, rc.classes.document);
                    \\    if (doc_ptr{d} == null) return w.EXCEPTION;
                    \\    const doc{d}: *z.HTMLDocument = @ptrCast(@alignCast(doc_ptr{d}));
                    \\    const root{d} = z.documentRoot(doc{d});
                    \\    if (root{d} == null) return w.EXCEPTION;
                    \\    const arg{d} = root{d}.?;
                    \\
                , .{ i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i, i });
            },
            .this_document => {
                // Try Document first, then OwnedDocument
                try writer.print(
                    \\    const arg{d}: *z.HTMLDocument = blk: {{
                    \\        if (qjs.JS_GetOpaque(this_val, rc.classes.document)) |ptr| break :blk @ptrCast(@alignCast(ptr));
                    \\        if (qjs.JS_GetOpaque(this_val, rc.classes.owned_document)) |ptr| break :blk @ptrCast(@alignCast(ptr));
                    \\        return ctx.throwTypeError("Method called on object that is not a Document (Class ID mismatch)");
                    // \\        return w.EXCEPTION;
                    \\    }};
                    \\
                , .{i});
            },
            .element => {
                // Use rc.classes.dom_node (generic check) or strict?
                try writer.print(
                    \\    const elem_arg_ptr{d} = qjs.JS_GetOpaque(argv[{d}], rc.classes.dom_node);
                    \\    if (elem_arg_ptr{d} == null) return ctx.throwTypeError("Argument {d} must be a DOM Element");
                    \\    const arg{d}: *z.HTMLElement = @ptrCast(@alignCast(elem_arg_ptr{d}));
                    \\
                , .{ i, js_arg_idx, i, js_arg_idx, i, i });
                js_arg_idx += 1;
            },
            .node => {
                try writer.print(
                    \\    const arg{d}_opt = DOMBridge.unwrapNode(ctx, argv[{d}]);
                    \\    if (arg{d}_opt  == null) return ctx.throwTypeError("Argument {d} must be a Node");
                    \\    const arg{d} = arg{d}_opt.?;
                    \\
                , .{ i, js_arg_idx, i, js_arg_idx, i, i });
                js_arg_idx += 1;
            },
            .this_parser => {
                // Uses rc.classes.dom_parser
                try writer.print(
                    \\    const ptr{d} = qjs.JS_GetOpaque(this_val, rc.classes.dom_parser);
                    \\    if (ptr{d} == null) return ctx.throwTypeError("Object is not a DOMParser");
                    \\    const arg{d}: *z.DOMParser = @ptrCast(@alignCast(ptr{d}));
                    \\
                , .{ i, i, i, i });
            },
            .string => {
                try writer.print(
                    \\    const arg{d} = ctx.toZString(argv[{d}]) catch return w.EXCEPTION;
                    \\    defer ctx.freeZString(arg{d});
                    \\
                , .{ i, js_arg_idx, i });
                js_arg_idx += 1;
            },
            .int32 => {
                try writer.print(
                    \\    var arg{d}: i32 = 0;
                    \\    if (qjs.JS_ToInt32(ctx_ptr, &arg{d}, argv[{d}]) != 0) return w.EXCEPTION;
                    \\
                , .{ i, i, js_arg_idx });
                js_arg_idx += 1;
            },
            .uint32 => {
                try writer.print(
                    \\    var arg{d}: u32 = 0;
                    \\    if (qjs.JS_ToUint32(ctx_ptr, &arg{d}, argv[{d}]) != 0) return w.EXCEPTION;
                    \\
                , .{ i, i, js_arg_idx });
                js_arg_idx += 1;
            },
            .boolean => {
                try writer.print("    const arg{d} = qjs.JS_ToBool(ctx_ptr, argv[{d}]) != 0;\n", .{ i, js_arg_idx });
                js_arg_idx += 1;
            },
        }
    }

    // 4. CALL NATIVE FUNCTION
    try writer.writeAll("    // Call native Zig function\n");

    // Special case: setAttribute returns a value we need to discard
    // TODO: refactor to return !void from Zig side
    // const is_set_attribute = std.mem.eql(u8, func.name, "setAttribute");

    if (func.return_type != .void_type and func.return_type != .void_with_error) {
        try writer.writeAll("    const result = ");
    } else {
        try writer.writeAll("    ");
    }

    // Call
    try writer.print("{s}(", .{func.zig_func_name});
    for (func.args, 0..) |_, i| {
        if (i > 0) try writer.writeAll(", ");
        try writer.print("arg{d}", .{i});
    }
    try writer.writeAll(")");

    // Catch errors for non-void returns that are errors
    if (func.return_type == .element or
        func.return_type == .node or
        func.return_type == .error_string or
        func.return_type == .error_document or
        func.return_type == .void_with_error or
        func.return_type == .error_owned_document)
    {
        try writer.writeAll(
            \\ catch |err| {
            \\     if (@errorReturnTrace()) |trace| {
            \\         std.debug.dumpStackTrace(trace.*);
            \\     }
            \\     std.debug.print("JS Binding Error: {}\n", .{err});
            \\     return ctx.throwTypeError("Native Zig Error");
            \\ }
        );
    } else if (func.return_type == .void_type) {
        // For void functions, only catch errors for specific functions we know return errors
        const is_set_attribute = std.mem.eql(u8, func.name, "setAttribute");
        const is_remove_attr = std.mem.eql(u8, func.name, "removeAttribute");
        const is_set_content = std.mem.eql(u8, func.name, "setContentAsText");
        const is_set_inner = std.mem.eql(u8, func.name, "setInnerHTML");
        const is_add_evt = std.mem.eql(u8, func.name, "addEventListener");
        const is_dispatch = std.mem.eql(u8, func.name, "dispatchEvent");

        if (is_remove_attr or is_set_content or is_set_inner or is_add_evt or is_dispatch or is_set_attribute) {
            try writer.writeAll(" catch return w.EXCEPTION");
        }
        // if (is_remove_attr or is_set_content or is_set_inner) {
        //     try writer.writeAll(" catch return w.EXCEPTION");
        // }
    }
    try writer.writeAll(";\n\n");

    // 5. RETURN VALUE
    switch (func.return_type) {
        .void_type, .void_with_error => try writer.writeAll("    return w.UNDEFINED;\n"),

        .element => try writer.writeAll("    return DOMBridge.wrapElement(ctx, result) catch w.EXCEPTION;\n"),
        .node => try writer.writeAll("    return DOMBridge.wrapNode(ctx, result) catch w.EXCEPTION;\n"),

        .optional_element => try writer.writeAll("    if (result) |elem| { return DOMBridge.wrapElement(ctx, elem) catch w.EXCEPTION; } else { return w.NULL; }\n"),
        .optional_node => try writer.writeAll("    if (result) |node| { return DOMBridge.wrapNode(ctx, node) catch w.EXCEPTION; } else { return w.NULL; }\n"),

        .string, .error_string => {
            if (allocator_idx) |idx| {
                try writer.print("    defer arg{d}.free(result);\n    return ctx.newString(result);\n", .{idx});
            } else {
                try writer.writeAll("    return ctx.newString(result);\n");
            }
        },
        .optional_string => try writer.writeAll("    if (result) |str| { return ctx.newString(str); } else { return w.NULL; }\n"),
        .int32 => try writer.writeAll("    return ctx.newInt32(result);\n"),
        .uint32 => try writer.writeAll("    return ctx.newUint32(result);\n"),
        .boolean => try writer.writeAll("    return ctx.newBool(result);\n"),

        .document, .error_document => {
            // Use rc.classes.document instead of z.dom_class_id.*
            try writer.writeAll(
                \\    const doc_obj = qjs.JS_NewObjectClass(ctx_ptr, @intCast(rc.classes.document));
                \\    _ = qjs.JS_SetOpaque(doc_obj, @ptrCast(result));
                \\    return doc_obj;
                \\
            );
        },
        .owned_document, .error_owned_document => {
            // [NEW] Use rc.classes.owned_document (which has the finalizer)
            try writer.writeAll(
                \\    const doc_obj = qjs.JS_NewObjectClass(ctx_ptr, @intCast(rc.classes.owned_document));
                \\    _ = qjs.JS_SetOpaque(doc_obj, @ptrCast(result));
                \\    return doc_obj;
                \\
            );
        },
    }

    try writer.writeAll("}\n");
}
