//! Build-time async binding generator
//! Generates async bindings using auto_bridge pattern
//!
//! Usage: zig run tools/gen_async_bindings.zig -- src/async_bindings_generated.zig

const std = @import("std");

/// Specification for a standard (synchronous) C function binding
const StandardBindingSpec = struct {
    name: []const u8, // JavaScript function name
    c_func: []const u8, // e.g., "js_setTimeout"
    arg_count: usize, // Number of JS arguments
};

/// Specification for an async binding (using auto_bridge)
const AsyncBindingSpec = struct {
    name: []const u8, // JavaScript function name
    payload_type: []const u8, // e.g., "Worker.FetchPayload"
    worker_func: []const u8, // e.g., "Worker.workerFetch"
    arg_count: usize, // Number of JS arguments
};

/// Standard EventLoop bindings (timers, etc.)
const standard_bindings = [_]StandardBindingSpec{
    .{ .name = "setTimeout", .c_func = "js_setTimeout", .arg_count = 2 },
    .{ .name = "setInterval", .c_func = "js_setInterval", .arg_count = 2 },
    .{ .name = "clearTimeout", .c_func = "js_clearTimeout", .arg_count = 1 },
    .{ .name = "clearInterval", .c_func = "js_clearTimeout", .arg_count = 1 }, // Same impl
};

/// Async worker bindings (using auto_bridge)
const async_bindings = [_]AsyncBindingSpec{
    .{
        .name = "fetch",
        .payload_type = "Worker.FetchPayload",
        .worker_func = "Worker.workerFetch",
        .arg_count = 1,
    },
    .{
        .name = "simulateWork",
        .payload_type = "Worker.SimulateWorkPayload",
        .worker_func = "Worker.workerSimulateAsync",
        .arg_count = 1,
    },
    .{
        .name = "readFile",
        .payload_type = "Worker.ReadFilePayload",
        .worker_func = "Worker.workerReadFile",
        .arg_count = 1,
    },
    // Add more async bindings here as needed
};

pub fn main() !void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    const args = try std.process.argsAlloc(allocator);
    if (args.len < 2) {
        std.debug.print("Usage: {s} <output_file>\n", .{args[0]});
        return;
    }

    const output_file_path = args[1];

    // Build output in memory
    var output = std.ArrayListUnmanaged(u8){};
    defer output.deinit(allocator);
    const writer = output.writer(allocator);

    // Generate file header
    try writer.writeAll(
        \\// THIS FILE IS AUTO-GENERATED BY tools/gen_async_bindings.zig
        \\// DO NOT EDIT MANUALLY
        \\
        \\const AutoBridge = @import("auto_bridge.zig");
        \\const Worker = @import("Worker.zig");
        \\const zqjs = @import("wrapper.zig");
        \\const Timers = @import("timers.zig");
        \\
        \\
    );

    // Generate bindings
    try writer.writeAll("// Auto-generated async bindings\n");
    for (async_bindings) |binding| {
        try writer.print(
            \\/// {s}() -> Promise<string>
            \\/// Auto-generated async binding
            \\pub const js_{s} = AutoBridge.bindAsyncAuto(
            \\    {s},
            \\    {s},
            \\);
            \\
            \\
        ,
            .{
                binding.name,
                binding.name,
                binding.payload_type,
                binding.worker_func,
            },
        );
    }

    // Generate installer function
    try writer.writeAll(
        \\
        \\/// Install all EventLoop bindings (standard + async)
        \\pub fn installAllBindings(ctx: zqjs.Context, global: zqjs.Value) !void {
        \\
    );

    // Install standard bindings (timers, etc.)
    try writer.writeAll("    // Standard EventLoop APIs (timers)\n");
    for (standard_bindings) |binding| {
        try writer.print(
            \\    const {s}_fn = ctx.newCFunction(Timers.{s}, "{s}", {d});
            \\    _ = try ctx.setPropertyStr(global, "{s}", {s}_fn);
            \\
        ,
            .{
                binding.name,
                binding.c_func,
                binding.name,
                binding.arg_count,
                binding.name,
                binding.name,
            },
        );
    }

    // Install async bindings
    try writer.writeAll(
        \\
        \\    // Async worker APIs
        \\
    );
    for (async_bindings) |binding| {
        try writer.print(
            \\    const {s}_fn = ctx.newCFunction(js_{s}, "{s}", {d});
            \\    _ = try ctx.setPropertyStr(global, "{s}", {s}_fn);
            \\
        ,
            .{
                binding.name,
                binding.name,
                binding.name,
                binding.arg_count,
                binding.name,
                binding.name,
            },
        );
    }

    try writer.writeAll("}\n");

    // Write to file
    const file = try std.fs.cwd().createFile(output_file_path, .{});
    defer file.close();
    try file.writeAll(output.items);

    std.debug.print("Generated {d} standard + {d} async bindings to {s}\n", .{
        standard_bindings.len,
        async_bindings.len,
        output_file_path,
    });
}
