//! Build-time QuickJS binding generator
//! Generates C-compatible wrappers for Zig functions automatically
//!
//! Usage: zig run tools/gen_bindings.zig -- src/bindings_generated.zig

const std = @import("std");

// We can't import root.zig at comptime in a build tool, so we define types locally
// These must match your actual types
const HTMLDocument = opaque {};
const DomNode = opaque {};
const HTMLElement = opaque {};

// List of functions to bind - manual registry
const BindingSpec = struct {
    name: []const u8,
    zig_func_name: []const u8, // Name in z.* namespace

    // Manually specify signature (can't do @TypeOf in build tool)
    args: []const ArgType,
    return_type: ReturnType,
};

const ArgType = union(enum) {
    allocator,
    this_element, // *HTMLElement from 'this'
    this_node, // *DomNode from 'this'
    document, // *HTMLDocument global singleton
    string, // []const u8
    int32, // i32
    uint32, // u32
    boolean, // bool
};

const ReturnType = union(enum) {
    void_type,
    element, // *HTMLElement
    node, // *DomNode
    string, // []const u8
    int32, // i32
    uint32, // u32
    boolean, // bool

    error_void, // !void
    error_element, // !*HTMLElement
    error_node, // !*DomNode
    error_string, // ![]const u8
};

// Define your API surface - manually specify each binding
const api_functions = [_]BindingSpec{
    // createElement(doc: *HTMLDocument, tag_name: []const u8) !*HTMLElement
    .{
        .name = "createElement",
        .zig_func_name = "createElement",
        .args = &[_]ArgType{ .document, .string },
        .return_type = .error_element,
    },

    // setAttribute(elem: *HTMLElement, name: []const u8, value: []const u8) !void
    .{
        .name = "setAttribute",
        .zig_func_name = "setAttribute",
        .args = &[_]ArgType{ .this_element, .string, .string },
        .return_type = .error_void,
    },

    // appendChild(parent: *DomNode, child: *DomNode) !void
    .{
        .name = "appendChild",
        .zig_func_name = "appendChild",
        .args = &[_]ArgType{ .this_node, .this_node },
        .return_type = .error_void,
    },

    // textContent(node: *DomNode, allocator: Allocator) ![]const u8
    .{
        .name = "textContent",
        .zig_func_name = "textContent",
        .args = &[_]ArgType{ .this_node, .allocator },
        .return_type = .error_string,
    },

    // Add more functions here...
};

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const args = try std.process.argsAlloc(allocator);
    defer std.process.argsFree(allocator, args);

    if (args.len != 2) {
        std.debug.print("Usage: {s} <output_path>\n", .{args[0]});
        std.debug.print("Example: zig run tools/gen_bindings.zig -- src/bindings_generated.zig\n", .{});
        return error.InvalidArgs;
    }

    const out_path = args[1];

    std.debug.print("Generating bindings to: {s}\n", .{out_path});
    std.debug.print("Binding {d} functions...\n", .{api_functions.len});

    // Build all content in memory first, then write to file
    var output: std.ArrayList(u8) = .empty;
    defer output.deinit(allocator);
    const writer = output.writer(allocator);

    try writeHeader(writer);

    for (api_functions) |spec| {
        try generateWrapper(writer, spec);
    }

    try writeFooter(writer);

    // Write to file
    try std.fs.cwd().writeFile(.{ .sub_path = out_path, .data = output.items });
    std.debug.print("✓ Generated {d} bindings successfully!\n", .{api_functions.len});
}

fn writeHeader(writer: anytype) !void {
    try writer.writeAll(
        \\// THIS FILE IS AUTO-GENERATED BY tools/gen_bindings.zig
        \\// DO NOT EDIT MANUALLY - Your changes will be overwritten!
        \\//
        \\// To regenerate: zig build gen-bindings
        \\
        \\const std = @import("std");
        \\const z = @import("root.zig");
        \\const w = @import("wrapper.zig");
        \\const qjs = z.qjs;
        \\
        \\// Import helpers
        \\const getAllocator = @import("js_native_bridge.zig").getAllocator;
        \\const DOMBridge = @import("dom_bridge.zig").DOMBridge;
        \\const dom_class_id = @import("dom_bridge.zig").dom_class_id;
        \\
        \\
    );
}

fn writeFooter(writer: anytype) !void {
    try writer.writeAll(
        \\
        \\// Helper to install all generated bindings
        \\pub fn installAllBindings(ctx: ?*qjs.JSContext, target: qjs.JSValue) !void {
        \\    const c = w.Context{ .ptr = ctx };
        \\
    );

    for (api_functions) |spec| {
        try writer.print(
            \\    try c.setPropertyStr(target, "{s}", c.newCFunction(js_{s}, "{s}", {d}));
            \\
        , .{ spec.name, spec.name, spec.name, countJSArgs(spec.args) });
    }

    try writer.writeAll(
        \\}
        \\
    );
}

fn countJSArgs(args: []const ArgType) u32 {
    var count: u32 = 0;
    for (args) |arg| {
        switch (arg) {
            .allocator, .document, .this_element, .this_node => {},
            else => count += 1,
        }
    }
    return count;
}

fn generateWrapper(writer: anytype, spec: BindingSpec) !void {
    try writer.print(
        \\/// Generated wrapper for z.{s}
        \\pub fn js_{s}(
        \\    ctx_ptr: ?*qjs.JSContext,
        \\    this_val: qjs.JSValue,
        \\    argc: c_int,
        \\    argv: [*c]qjs.JSValue,
        \\) callconv(.c) qjs.JSValue {{
        \\    const ctx = w.Context{{ .ptr = ctx_ptr }};
        \\
    , .{ spec.zig_func_name, spec.name });

    // Check argument count
    const expected_js_args = countJSArgs(spec.args);
    if (expected_js_args > 0) {
        try writer.print(
            \\    if (argc < {d}) return z.jsException; // Not enough arguments
            \\
        , .{expected_js_args});
    } else {
        try writer.writeAll(
            \\    _ = argc;
            \\    _ = argv;
            \\
        );
    }

    // Handle unused this_val if not needed
    const uses_this = blk: {
        for (spec.args) |arg| {
            if (arg == .this_element or arg == .this_node) break :blk true;
        }
        break :blk false;
    };
    if (!uses_this) {
        try writer.writeAll("    _ = this_val;\n");
    }

    try writer.writeAll("\n");

    // Generate argument unpacking
    var js_arg_idx: u32 = 0;
    for (spec.args, 0..) |arg, i| {
        try generateArgUnpack(writer, arg, i, &js_arg_idx);
    }

    // Call the Zig function
    try writer.writeAll("\n    // Call native Zig function\n");

    const has_return = switch (spec.return_type) {
        .void_type, .error_void => false,
        else => true,
    };

    if (has_return) {
        try writer.writeAll("    const result = ");
    } else {
        try writer.writeAll("    ");
    }

    try writer.print("z.{s}(", .{spec.zig_func_name});

    for (spec.args, 0..) |_, i| {
        if (i > 0) try writer.writeAll(", ");
        try writer.print("arg{d}", .{i});
    }
    try writer.writeAll(")");

    // Handle errors
    const is_error_union = switch (spec.return_type) {
        .error_void, .error_element, .error_node, .error_string => true,
        else => false,
    };

    if (is_error_union) {
        try writer.writeAll(" catch return z.jsException;\n");
    } else {
        try writer.writeAll(";\n");
    }

    // Free temporary strings allocated during arg unpacking
    for (spec.args, 0..) |arg, i| {
        if (arg == .string) {
            try writer.print("    ctx.freeZString(arg{d});\n", .{i});
        }
    }

    // Marshal return value
    try writer.writeAll("\n");
    try generateReturnMarshalling(writer, spec.return_type);

    try writer.writeAll("}\n\n");
}

fn generateArgUnpack(writer: anytype, arg: ArgType, idx: usize, js_arg_idx: *u32) !void {
    switch (arg) {
        .allocator => {
            try writer.print(
                \\    const arg{d} = getAllocator(ctx_ptr);
                \\
            , .{idx});
        },

        .document => {
            try writer.print(
                \\    // Get document from global scope
                \\    const global{d} = ctx.getGlobalObject();
                \\    defer ctx.freeValue(global{d});
                \\    const doc_obj{d} = ctx.getPropertyStr(global{d}, "document");
                \\    defer ctx.freeValue(doc_obj{d});
                \\    const native_doc{d} = ctx.getPropertyStr(doc_obj{d}, "_native_doc");
                \\    defer ctx.freeValue(native_doc{d});
                \\    const doc_ptr{d} = qjs.JS_GetOpaque(native_doc{d}, dom_class_id);
                \\    if (doc_ptr{d} == null) return z.jsException;
                \\    const arg{d}: *z.HTMLDocument = @ptrCast(@alignCast(doc_ptr{d}));
                \\
            , .{ idx, idx, idx, idx, idx, idx, idx, idx, idx, idx, idx });
        },

        .this_element => {
            try writer.print(
                \\    // Get native element from 'this'
                \\    const native_prop{d} = ctx.getPropertyStr(this_val, "_native_element");
                \\    defer ctx.freeValue(native_prop{d});
                \\    const elem_ptr{d} = qjs.JS_GetOpaque(native_prop{d}, dom_class_id);
                \\    if (elem_ptr{d} == null) return z.jsException;
                \\    const arg{d}: *z.HTMLElement = @ptrCast(@alignCast(elem_ptr{d}));
                \\
            , .{ idx, idx, idx, idx, idx, idx, idx });
        },

        .this_node => {
            try writer.print(
                \\    // Get native node from 'this'
                \\    const native_prop{d} = ctx.getPropertyStr(this_val, "_native_element");
                \\    defer ctx.freeValue(native_prop{d});
                \\    const node_ptr{d} = qjs.JS_GetOpaque(native_prop{d}, dom_class_id);
                \\    if (node_ptr{d} == null) return z.jsException;
                \\    const arg{d}: *z.DomNode = @ptrCast(@alignCast(node_ptr{d}));
                \\
            , .{ idx, idx, idx, idx, idx, idx, idx });
        },

        .string => {
            try writer.print(
                \\    const arg{d} = ctx.toZString(argv[{d}]) catch return z.jsException;
                \\
            , .{ idx, js_arg_idx.* });
            js_arg_idx.* += 1;
        },

        .int32 => {
            try writer.print(
                \\    const arg{d} = ctx.toInt32(argv[{d}]) catch return z.jsException;
                \\
            , .{ idx, js_arg_idx.* });
            js_arg_idx.* += 1;
        },

        .uint32 => {
            try writer.print(
                \\    const arg{d} = ctx.toUint32(argv[{d}]) catch return z.jsException;
                \\
            , .{ idx, js_arg_idx.* });
            js_arg_idx.* += 1;
        },

        .boolean => {
            try writer.print(
                \\    const arg{d} = ctx.toBool(argv[{d}]);
                \\
            , .{ idx, js_arg_idx.* });
            js_arg_idx.* += 1;
        },
    }
}

fn generateReturnMarshalling(writer: anytype, return_type: ReturnType) !void {
    switch (return_type) {
        .void_type, .error_void => {
            try writer.writeAll("    return z.jsUndefined;\n");
        },

        .element, .error_element => {
            try writer.writeAll(
                \\    return DOMBridge.wrapElement(ctx_ptr, result) catch z.jsException;
                \\
            );
        },

        .node, .error_node => {
            try writer.writeAll(
                \\    // TODO: Implement node wrapping
                \\    return z.jsUndefined;
                \\
            );
        },

        .string, .error_string => {
            try writer.writeAll(
                \\    defer ctx.freeZString(result);
                \\    return ctx.newString(result);
                \\
            );
        },

        .int32, .uint32 => {
            try writer.writeAll(
                \\    return ctx.newInt32(result);
                \\
            );
        },

        .boolean => {
            try writer.writeAll(
                \\    return ctx.newBool(result);
                \\
            );
        },
    }
}
