// THIS FILE IS AUTO-GENERATED BY tools/gen_async_bindings.zig
// DO NOT EDIT MANUALLY

const AutoBridge = @import("auto_bridge.zig");
const AsyncBridge = @import("async_bridge.zig");
const workers = @import("workers.zig");
const zqjs = @import("wrapper.zig");

// Auto-generated async bindings
/// readFile() -> Promise<string>
/// Auto-generated async binding
pub const js_readFile = AutoBridge.bindAsyncAuto(
    workers.ReadFilePayload,
    workers.workerReadFile,
);


/// Install Async Worker bindings
pub fn installAllBindings(ctx: zqjs.Context, global: zqjs.Value) !void {
    // Async worker APIs
    const readFile_fn = ctx.newCFunction(js_readFile, "readFile", 1);
    _ = try ctx.setPropertyStr(global, "readFile", readFile_fn);
}
