// THIS FILE IS AUTO-GENERATED BY tools/gen_async_bindings.zig
// DO NOT EDIT MANUALLY

const AutoBridge = @import("auto_bridge.zig");
const Worker = @import("Worker.zig");
const zqjs = @import("wrapper.zig");
const Timers = @import("timers.zig");

// Auto-generated async bindings
/// fetch() -> Promise<string>
/// Auto-generated async binding
pub const js_fetch = AutoBridge.bindAsyncAuto(
    Worker.FetchPayload,
    Worker.workerFetch,
);

/// simulateWork() -> Promise<string>
/// Auto-generated async binding
pub const js_simulateWork = AutoBridge.bindAsyncAuto(
    Worker.SimulateWorkPayload,
    Worker.workerSimulateAsync,
);

/// readFile() -> Promise<string>
/// Auto-generated async binding
pub const js_readFile = AutoBridge.bindAsyncAuto(
    Worker.ReadFilePayload,
    Worker.workerReadFile,
);


/// Install all EventLoop bindings (standard + async)
pub fn installAllBindings(ctx: zqjs.Context, global: zqjs.Value) !void {
    // Standard EventLoop APIs (timers)
    const setTimeout_fn = ctx.newCFunction(Timers.js_setTimeout, "setTimeout", 2);
    _ = try ctx.setPropertyStr(global, "setTimeout", setTimeout_fn);
    const setInterval_fn = ctx.newCFunction(Timers.js_setInterval, "setInterval", 2);
    _ = try ctx.setPropertyStr(global, "setInterval", setInterval_fn);
    const clearTimeout_fn = ctx.newCFunction(Timers.js_clearTimeout, "clearTimeout", 1);
    _ = try ctx.setPropertyStr(global, "clearTimeout", clearTimeout_fn);
    const clearInterval_fn = ctx.newCFunction(Timers.js_clearTimeout, "clearInterval", 1);
    _ = try ctx.setPropertyStr(global, "clearInterval", clearInterval_fn);

    // Async worker APIs
    const fetch_fn = ctx.newCFunction(js_fetch, "fetch", 1);
    _ = try ctx.setPropertyStr(global, "fetch", fetch_fn);
    const simulateWork_fn = ctx.newCFunction(js_simulateWork, "simulateWork", 1);
    _ = try ctx.setPropertyStr(global, "simulateWork", simulateWork_fn);
    const readFile_fn = ctx.newCFunction(js_readFile, "readFile", 1);
    _ = try ctx.setPropertyStr(global, "readFile", readFile_fn);
}
