// THIS FILE IS AUTO-GENERATED BY tools/gen_bindings.zig
// DO NOT EDIT MANUALLY

const std = @import("std");
const z = @import("root.zig");
const w = @import("wrapper.zig");
const qjs = z.qjs;
const DOMBridge = @import("dom_bridge.zig").DOMBridge;
const RuntimeContext = @import("runtime_context.zig").RuntimeContext;


/// Generated wrapper for z.parseHTML
pub fn js_parseHTML(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 1) return w.EXCEPTION;
    _ = this_val;
    const arg0 = rc.allocator;
    const arg1 = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(arg1);
    // Call native Zig function
    const result = z.parseHTML(arg0, arg1) catch |err| {
     if (@errorReturnTrace()) |trace| {
         std.debug.dumpStackTrace(trace.*);
     }
     std.debug.print("JS Binding Error: {}\n", .{err});
     return ctx.throwTypeError("Native Zig Error");
 };

    const doc_obj = qjs.JS_NewObjectClass(ctx_ptr, @intCast(rc.classes.owned_document));
    _ = qjs.JS_SetOpaque(doc_obj, @ptrCast(result));
    return doc_obj;
}

/// Generated wrapper for z.documentRoot
pub fn js_documentRoot(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    _ = argc; _ = argv;
    _ = this_val;
    const global0 = ctx.getGlobalObject();
    defer ctx.freeValue(global0);
    const doc_obj0 = ctx.getPropertyStr(global0, "document");
    defer ctx.freeValue(doc_obj0);
    const native_doc0 = ctx.getPropertyStr(doc_obj0, "_native_doc");
    defer ctx.freeValue(native_doc0);
    const doc_ptr0 = qjs.JS_GetOpaque(native_doc0, rc.classes.document);
    if (doc_ptr0 == null) return w.EXCEPTION;
    const arg0: *z.HTMLDocument = @ptrCast(@alignCast(doc_ptr0));
    // Call native Zig function
    const result = z.documentRoot(arg0);

    if (result) |node| { return DOMBridge.wrapNode(ctx, node) catch w.EXCEPTION; } else { return w.NULL; }
}

/// Generated wrapper for z.ownerDocument
pub fn js_ownerDocument(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    _ = argc; _ = argv;
    const arg0_opt = DOMBridge.unwrapNode(ctx, this_val);
    if (arg0_opt == null) return ctx.throwTypeError("'this' is not a Node (or unwrap failed)");
    const arg0 = arg0_opt.?;
    // Call native Zig function
    const result = z.ownerDocument(arg0);

    const doc_obj = qjs.JS_NewObjectClass(ctx_ptr, @intCast(rc.classes.document));
    _ = qjs.JS_SetOpaque(doc_obj, @ptrCast(result));
    return doc_obj;
}

/// Generated wrapper for z.createElement
pub fn js_createElement(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 1) return w.EXCEPTION;
    const arg0: *z.HTMLDocument = blk: {
        if (qjs.JS_GetOpaque(this_val, rc.classes.document)) |ptr| break :blk @ptrCast(@alignCast(ptr));
        if (qjs.JS_GetOpaque(this_val, rc.classes.owned_document)) |ptr| break :blk @ptrCast(@alignCast(ptr));
        return ctx.throwTypeError("Method called on object that is not a Document (Class ID mismatch)");
    };
    const arg1 = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(arg1);
    // Call native Zig function
    const result = z.createElement(arg0, arg1) catch |err| {
     if (@errorReturnTrace()) |trace| {
         std.debug.dumpStackTrace(trace.*);
     }
     std.debug.print("JS Binding Error: {}\n", .{err});
     return ctx.throwTypeError("Native Zig Error");
 };

    return DOMBridge.wrapElement(ctx, result) catch w.EXCEPTION;
}

/// Generated wrapper for z.createTextNode
pub fn js_createTextNode(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 1) return w.EXCEPTION;
    const arg0: *z.HTMLDocument = blk: {
        if (qjs.JS_GetOpaque(this_val, rc.classes.document)) |ptr| break :blk @ptrCast(@alignCast(ptr));
        if (qjs.JS_GetOpaque(this_val, rc.classes.owned_document)) |ptr| break :blk @ptrCast(@alignCast(ptr));
        return ctx.throwTypeError("Method called on object that is not a Document (Class ID mismatch)");
    };
    const arg1 = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(arg1);
    // Call native Zig function
    const result = z.createTextNode(arg0, arg1) catch |err| {
     if (@errorReturnTrace()) |trace| {
         std.debug.dumpStackTrace(trace.*);
     }
     std.debug.print("JS Binding Error: {}\n", .{err});
     return ctx.throwTypeError("Native Zig Error");
 };

    return DOMBridge.wrapNode(ctx, result) catch w.EXCEPTION;
}

/// Generated wrapper for z.getElementById
pub fn js_getElementById(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 1) return w.EXCEPTION;
    const arg0: *z.HTMLDocument = blk: {
        if (qjs.JS_GetOpaque(this_val, rc.classes.document)) |ptr| break :blk @ptrCast(@alignCast(ptr));
        if (qjs.JS_GetOpaque(this_val, rc.classes.owned_document)) |ptr| break :blk @ptrCast(@alignCast(ptr));
        return ctx.throwTypeError("Method called on object that is not a Document (Class ID mismatch)");
    };
    const arg1 = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(arg1);
    // Call native Zig function
    const result = z.getElementById(arg0, arg1);

    if (result) |elem| { return DOMBridge.wrapElement(ctx, elem) catch w.EXCEPTION; } else { return w.NULL; }
}

/// Generated wrapper for z.DOMParser.parseFromString
pub fn js_parseFromString(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 1) return w.EXCEPTION;
    const ptr0 = qjs.JS_GetOpaque(this_val, rc.classes.dom_parser);
    if (ptr0 == null) return ctx.throwTypeError("Object is not a DOMParser");
    const arg0: *z.DOMParser = @ptrCast(@alignCast(ptr0));
    const arg1 = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(arg1);
    // Call native Zig function
    const result = z.DOMParser.parseFromString(arg0, arg1) catch |err| {
     if (@errorReturnTrace()) |trace| {
         std.debug.dumpStackTrace(trace.*);
     }
     std.debug.print("JS Binding Error: {}\n", .{err});
     return ctx.throwTypeError("Native Zig Error");
 };

    const doc_obj = qjs.JS_NewObjectClass(ctx_ptr, @intCast(rc.classes.owned_document));
    _ = qjs.JS_SetOpaque(doc_obj, @ptrCast(result));
    return doc_obj;
}

// Property Getter for type
pub fn js_get_type(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.event);
    if (ptr == null) return ctx.throwTypeError("Object is not an Event");
    const this_arg: *z.events.DomEvent = @ptrCast(@alignCast(ptr));
    const result = z.events.getType(this_arg);
    return ctx.newString(result);
}

// Property Getter for bubbles
pub fn js_get_bubbles(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.event);
    if (ptr == null) return ctx.throwTypeError("Object is not an Event");
    const this_arg: *z.events.DomEvent = @ptrCast(@alignCast(ptr));
    const result = z.events.getBubbles(this_arg);
    return ctx.newBool(result);
}

// Property Getter for target
pub fn js_get_target(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.event);
    if (ptr == null) return ctx.throwTypeError("Object is not an Event");
    const this_arg: *z.events.DomEvent = @ptrCast(@alignCast(ptr));
    const result = z.events.getTarget(this_arg);
    if (result) |node| { return DOMBridge.wrapNode(ctx, node) catch w.EXCEPTION; } else { return w.NULL; }
}

// Property Getter for currentTarget
pub fn js_get_currentTarget(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.event);
    if (ptr == null) return ctx.throwTypeError("Object is not an Event");
    const this_arg: *z.events.DomEvent = @ptrCast(@alignCast(ptr));
    const result = z.events.getCurrentTarget(this_arg);
    if (result) |node| { return DOMBridge.wrapNode(ctx, node) catch w.EXCEPTION; } else { return w.NULL; }
}

/// Generated wrapper for z.events.stopPropagation
pub fn js_stopPropagation(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    _ = argc; _ = argv;
    const ptr0 = qjs.JS_GetOpaque(this_val, rc.classes.event);
    if (ptr0 == null) return ctx.throwTypeError("Object is not an Event");
    const arg0: *z.events.DomEvent = @ptrCast(@alignCast(ptr0));
    // Call native Zig function
    z.events.stopPropagation(arg0);

    return w.UNDEFINED;
}

/// Generated wrapper for z.events.preventDefault
pub fn js_preventDefault(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    _ = argc; _ = argv;
    const ptr0 = qjs.JS_GetOpaque(this_val, rc.classes.event);
    if (ptr0 == null) return ctx.throwTypeError("Object is not an Event");
    const arg0: *z.events.DomEvent = @ptrCast(@alignCast(ptr0));
    // Call native Zig function
    z.events.preventDefault(arg0);

    return w.UNDEFINED;
}

/// Generated wrapper for z.addEventListener
pub fn js_addEventListener(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 2) return w.EXCEPTION;
    const arg0 = ctx;
    const arg1: *DOMBridge = @ptrCast(@alignCast(rc.dom_bridge.?));
    const arg2_opt = DOMBridge.unwrapNode(ctx, this_val);
    if (arg2_opt == null) return ctx.throwTypeError("'this' is not a Node (or unwrap failed)");
    const arg2 = arg2_opt.?;
    const arg3 = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(arg3);
    const arg4 = argv[1];
    // Call native Zig function
    z.addEventListener(arg0, arg1, arg2, arg3, arg4) catch |err| {
     if (@errorReturnTrace()) |trace| {
         std.debug.dumpStackTrace(trace.*);
     }
     std.debug.print("JS Binding Error: {}\n", .{err});
     return ctx.throwTypeError("Native Zig Error");
 };

    return w.UNDEFINED;
}

/// Generated wrapper for z.removeEventListener
pub fn js_removeEventListener(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 2) return w.EXCEPTION;
    const arg0 = ctx;
    const arg1: *DOMBridge = @ptrCast(@alignCast(rc.dom_bridge.?));
    const arg2_opt = DOMBridge.unwrapNode(ctx, this_val);
    if (arg2_opt == null) return ctx.throwTypeError("'this' is not a Node (or unwrap failed)");
    const arg2 = arg2_opt.?;
    const arg3 = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(arg3);
    const arg4 = argv[1];
    // Call native Zig function
    z.removeEventListener(arg0, arg1, arg2, arg3, arg4) catch |err| {
     if (@errorReturnTrace()) |trace| {
         std.debug.dumpStackTrace(trace.*);
     }
     std.debug.print("JS Binding Error: {}\n", .{err});
     return ctx.throwTypeError("Native Zig Error");
 };

    return w.UNDEFINED;
}

/// Generated wrapper for z.dispatchEvent
pub fn js_dispatchEvent(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 1) return w.EXCEPTION;
    const arg0 = ctx;
    const arg1: *DOMBridge = @ptrCast(@alignCast(rc.dom_bridge.?));
    const arg2_opt = DOMBridge.unwrapNode(ctx, this_val);
    if (arg2_opt == null) return ctx.throwTypeError("'this' is not a Node (or unwrap failed)");
    const arg2 = arg2_opt.?;
    const arg3 = argv[0];
    // Call native Zig function
    const result = z.dispatchEvent(arg0, arg1, arg2, arg3) catch |err| {
     if (@errorReturnTrace()) |trace| {
         std.debug.dumpStackTrace(trace.*);
     }
     std.debug.print("JS Binding Error: {}\n", .{err});
     return ctx.throwTypeError("Native Zig Error");
 };

    return ctx.newBool(result);
}

/// Generated wrapper for z.cloneNode
pub fn js_cloneNode(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    if (argc < 1) return w.EXCEPTION;
    const arg0_opt = DOMBridge.unwrapNode(ctx, this_val);
    if (arg0_opt == null) return ctx.throwTypeError("'this' is not a Node (or unwrap failed)");
    const arg0 = arg0_opt.?;
    const arg1 = qjs.JS_ToBool(ctx_ptr, argv[0]) != 0;
    // Call native Zig function
    const result = z.cloneNode(arg0, arg1);

    if (result) |node| { return DOMBridge.wrapNode(ctx, node) catch w.EXCEPTION; } else { return w.NULL; }
}

/// Generated wrapper for z.appendChild
pub fn js_appendChild(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    if (argc < 1) return w.EXCEPTION;
    const arg0_opt = DOMBridge.unwrapNode(ctx, this_val);
    if (arg0_opt == null) return ctx.throwTypeError("'this' is not a Node (or unwrap failed)");
    const arg0 = arg0_opt.?;
    const arg1_opt = DOMBridge.unwrapNode(ctx, argv[0]);
    if (arg1_opt  == null) return ctx.throwTypeError("Argument 0 must be a Node");
    const arg1 = arg1_opt.?;
    // Call native Zig function
    z.appendChild(arg0, arg1);

    return w.UNDEFINED;
}

/// Generated wrapper for z.insertBefore
pub fn js_insertBefore(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    if (argc < 1) return w.EXCEPTION;
    const arg0_opt = DOMBridge.unwrapNode(ctx, this_val);
    if (arg0_opt == null) return ctx.throwTypeError("'this' is not a Node (or unwrap failed)");
    const arg0 = arg0_opt.?;
    const arg1_opt = DOMBridge.unwrapNode(ctx, argv[0]);
    if (arg1_opt  == null) return ctx.throwTypeError("Argument 0 must be a Node");
    const arg1 = arg1_opt.?;
    // Call native Zig function
    z.insertBefore(arg0, arg1);

    return w.UNDEFINED;
}

/// Generated wrapper for z.parentNode
pub fn js_parentNode(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    _ = argc; _ = argv;
    const arg0_opt = DOMBridge.unwrapNode(ctx, this_val);
    if (arg0_opt == null) return ctx.throwTypeError("'this' is not a Node (or unwrap failed)");
    const arg0 = arg0_opt.?;
    // Call native Zig function
    const result = z.parentNode(arg0);

    if (result) |node| { return DOMBridge.wrapNode(ctx, node) catch w.EXCEPTION; } else { return w.NULL; }
}

/// Generated wrapper for z.removeNode
pub fn js_remove(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    _ = argc; _ = argv;
    const arg0_opt = DOMBridge.unwrapNode(ctx, this_val);
    if (arg0_opt == null) return ctx.throwTypeError("'this' is not a Node (or unwrap failed)");
    const arg0 = arg0_opt.?;
    // Call native Zig function
    z.removeNode(arg0);

    return w.UNDEFINED;
}

/// Generated wrapper for z.setAttribute
pub fn js_setAttribute(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 2) return w.EXCEPTION;
    const elem_ptr0 = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (elem_ptr0 == null) return w.EXCEPTION;
    const arg0: *z.HTMLElement = @ptrCast(@alignCast(elem_ptr0));
    const arg1 = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(arg1);
    const arg2 = ctx.toZString(argv[1]) catch return w.EXCEPTION;
    defer ctx.freeZString(arg2);
    // Call native Zig function
    z.setAttribute(arg0, arg1, arg2) catch |err| {
     if (@errorReturnTrace()) |trace| {
         std.debug.dumpStackTrace(trace.*);
     }
     std.debug.print("JS Binding Error: {}\n", .{err});
     return ctx.throwTypeError("Native Zig Error");
 };

    return w.UNDEFINED;
}

/// Generated wrapper for z.getAttribute_zc
pub fn js_getAttribute(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 1) return w.EXCEPTION;
    const elem_ptr0 = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (elem_ptr0 == null) return w.EXCEPTION;
    const arg0: *z.HTMLElement = @ptrCast(@alignCast(elem_ptr0));
    const arg1 = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(arg1);
    // Call native Zig function
    const result = z.getAttribute_zc(arg0, arg1);

    if (result) |str| { return ctx.newString(str); } else { return w.NULL; }
}

/// Generated wrapper for z.removeAttribute
pub fn js_removeAttribute(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 1) return w.EXCEPTION;
    const elem_ptr0 = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (elem_ptr0 == null) return w.EXCEPTION;
    const arg0: *z.HTMLElement = @ptrCast(@alignCast(elem_ptr0));
    const arg1 = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(arg1);
    // Call native Zig function
    z.removeAttribute(arg0, arg1) catch |err| {
     if (@errorReturnTrace()) |trace| {
         std.debug.dumpStackTrace(trace.*);
     }
     std.debug.print("JS Binding Error: {}\n", .{err});
     return ctx.throwTypeError("Native Zig Error");
 };

    return w.UNDEFINED;
}

/// Generated wrapper for z.setHTML
pub fn js_setHTML(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 1) return w.EXCEPTION;
    const arg0 = rc.allocator;
    const elem_ptr1 = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (elem_ptr1 == null) return w.EXCEPTION;
    const arg1: *z.HTMLElement = @ptrCast(@alignCast(elem_ptr1));
    const arg2 = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(arg2);
    // Call native Zig function
    z.setHTML(arg0, arg1, arg2) catch |err| {
     if (@errorReturnTrace()) |trace| {
         std.debug.dumpStackTrace(trace.*);
     }
     std.debug.print("JS Binding Error: {}\n", .{err});
     return ctx.throwTypeError("Native Zig Error");
 };

    return w.UNDEFINED;
}

/// Generated wrapper for z.getHTML
pub fn js_getHTML(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    _ = argc; _ = argv;
    const arg0 = rc.allocator;
    const elem_ptr1 = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (elem_ptr1 == null) return w.EXCEPTION;
    const arg1: *z.HTMLElement = @ptrCast(@alignCast(elem_ptr1));
    // Call native Zig function
    const result = z.getHTML(arg0, arg1) catch |err| {
     if (@errorReturnTrace()) |trace| {
         std.debug.dumpStackTrace(trace.*);
     }
     std.debug.print("JS Binding Error: {}\n", .{err});
     return ctx.throwTypeError("Native Zig Error");
 };

    defer arg0.free(result);
    return ctx.newString(result);
}

// Property Getter for body
pub fn js_get_body(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const this_arg: *z.HTMLDocument = blk: {
        if (qjs.JS_GetOpaque(this_val, rc.classes.document)) |ptr| break :blk @ptrCast(@alignCast(ptr));
        if (qjs.JS_GetOpaque(this_val, rc.classes.owned_document)) |ptr| break :blk @ptrCast(@alignCast(ptr));
        return ctx.throwTypeError("Method called on object that is not a Document (Class ID mismatch)");
    };
    const result = z.bodyElement(this_arg);
    if (result) |elem| { return DOMBridge.wrapElement(ctx, elem) catch w.EXCEPTION; } else { return w.NULL; }
}

// Property Getter for textContent
pub fn js_get_textContent(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    _ = rc;
    const arg0_opt = DOMBridge.unwrapNode(ctx, this_val);
    if (arg0_opt == null) return w.EXCEPTION;
    const this_arg = arg0_opt.?;
    const result = z.textContent_zc(this_arg);
    return ctx.newString(result);
}

// Property Setter for textContent
pub fn js_set_textContent(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    _ = argc;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    _ = rc;
    const arg0_opt = DOMBridge.unwrapNode(ctx, this_val);
    if (arg0_opt == null) return ctx.throwTypeError("'this' is not a Node (unwrap failed)");
    const this_arg = arg0_opt.?;
    const val = argv[0];
    const val_str = ctx.toZString(val) catch return w.EXCEPTION;
    defer ctx.freeZString(val_str);
    z.setContentAsText(this_arg, val_str) catch |err| {
        std.debug.print("JS Setter Error (textContent): {}\n", .{err});
        return ctx.throwTypeError("Native Zig Error in Setter");
    };
    return w.UNDEFINED;
}

// Property Getter for nodeValue
pub fn js_get_nodeValue(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    _ = rc;
    const arg0_opt = DOMBridge.unwrapNode(ctx, this_val);
    if (arg0_opt == null) return w.EXCEPTION;
    const this_arg = arg0_opt.?;
    const result = z.nodeValue_zc(this_arg);
    return ctx.newString(result);
}

// Property Setter for nodeValue
pub fn js_set_nodeValue(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    _ = argc;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    _ = rc;
    const arg0_opt = DOMBridge.unwrapNode(ctx, this_val);
    if (arg0_opt == null) return ctx.throwTypeError("'this' is not a Node (unwrap failed)");
    const this_arg = arg0_opt.?;
    const val = argv[0];
    const val_str = ctx.toZString(val) catch return w.EXCEPTION;
    defer ctx.freeZString(val_str);
    z.setNodeValue(this_arg, val_str) catch |err| {
        std.debug.print("JS Setter Error (nodeValue): {}\n", .{err});
        return ctx.throwTypeError("Native Zig Error in Setter");
    };
    return w.UNDEFINED;
}

// Property Getter for innerText
pub fn js_get_innerText(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    _ = rc;
    const arg0_opt = DOMBridge.unwrapNode(ctx, this_val);
    if (arg0_opt == null) return w.EXCEPTION;
    const this_arg = arg0_opt.?;
    const result = z.textContent_zc(this_arg);
    return ctx.newString(result);
}

// Property Setter for innerText
pub fn js_set_innerText(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    _ = argc;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    _ = rc;
    const arg0_opt = DOMBridge.unwrapNode(ctx, this_val);
    if (arg0_opt == null) return ctx.throwTypeError("'this' is not a Node (unwrap failed)");
    const this_arg = arg0_opt.?;
    const val = argv[0];
    const val_str = ctx.toZString(val) catch return w.EXCEPTION;
    defer ctx.freeZString(val_str);
    z.setContentAsText(this_arg, val_str) catch |err| {
        std.debug.print("JS Setter Error (innerText): {}\n", .{err});
        return ctx.throwTypeError("Native Zig Error in Setter");
    };
    return w.UNDEFINED;
}

// Property Getter for innerHTML
pub fn js_get_innerHTML(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return ctx.throwTypeError("Object is not an HTMLElement");
    const this_arg: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const result = z.innerHTML(rc.allocator, this_arg) catch return w.EXCEPTION;
    defer rc.allocator.free(result);
    return ctx.newString(result);
}

// Property Setter for innerHTML
pub fn js_set_innerHTML(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    _ = argc;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return ctx.throwTypeError("Setter called on object that is not an HTMLElement");
    const this_arg: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const val = argv[0];
    const val_str = ctx.toZString(val) catch return w.EXCEPTION;
    defer ctx.freeZString(val_str);
    z.setInnerHTML(this_arg, val_str) catch |err| {
        std.debug.print("JS Setter Error (innerHTML): {}\n", .{err});
        return ctx.throwTypeError("Native Zig Error in Setter");
    };
    return w.UNDEFINED;
}

// Property Getter for content
pub fn js_get_content(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return ctx.throwTypeError("Object is not an HTMLElement");
    const this_arg: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const result = z.getTemplateContentAsNode(this_arg);
    if (result) |node| { return DOMBridge.wrapNode(ctx, node) catch w.EXCEPTION; } else { return w.NULL; }
}

// Property Getter for nextSibling
pub fn js_get_nextSibling(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    _ = rc;
    const arg0_opt = DOMBridge.unwrapNode(ctx, this_val);
    if (arg0_opt == null) return w.EXCEPTION;
    const this_arg = arg0_opt.?;
    const result = z.nextSibling(this_arg);
    if (result) |node| { return DOMBridge.wrapNode(ctx, node) catch w.EXCEPTION; } else { return w.NULL; }
}

// Property Getter for previousSibling
pub fn js_get_previousSibling(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    _ = rc;
    const arg0_opt = DOMBridge.unwrapNode(ctx, this_val);
    if (arg0_opt == null) return w.EXCEPTION;
    const this_arg = arg0_opt.?;
    const result = z.previousSibling(this_arg);
    if (result) |node| { return DOMBridge.wrapNode(ctx, node) catch w.EXCEPTION; } else { return w.NULL; }
}

// Property Getter for firstChild
pub fn js_get_firstChild(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    _ = rc;
    const arg0_opt = DOMBridge.unwrapNode(ctx, this_val);
    if (arg0_opt == null) return w.EXCEPTION;
    const this_arg = arg0_opt.?;
    const result = z.firstChild(this_arg);
    if (result) |node| { return DOMBridge.wrapNode(ctx, node) catch w.EXCEPTION; } else { return w.NULL; }
}

// Property Getter for lastChild
pub fn js_get_lastChild(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    _ = rc;
    const arg0_opt = DOMBridge.unwrapNode(ctx, this_val);
    if (arg0_opt == null) return w.EXCEPTION;
    const this_arg = arg0_opt.?;
    const result = z.lastChild(this_arg);
    if (result) |node| { return DOMBridge.wrapNode(ctx, node) catch w.EXCEPTION; } else { return w.NULL; }
}

// Property Getter for firstElementChild
pub fn js_get_firstElementChild(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    _ = rc;
    const arg0_opt = DOMBridge.unwrapNode(ctx, this_val);
    if (arg0_opt == null) return w.EXCEPTION;
    const this_arg = arg0_opt.?;
    const result = z.firstElementChild(this_arg);
    if (result) |elem| { return DOMBridge.wrapElement(ctx, elem) catch w.EXCEPTION; } else { return w.NULL; }
}

// Property Getter for nextElementSibling
pub fn js_get_nextElementSibling(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return ctx.throwTypeError("Object is not an HTMLElement");
    const this_arg: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const result = z.nextElementSibling(this_arg);
    if (result) |elem| { return DOMBridge.wrapElement(ctx, elem) catch w.EXCEPTION; } else { return w.NULL; }
}

// Property Getter for lastElementChild
pub fn js_get_lastElementChild(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return ctx.throwTypeError("Object is not an HTMLElement");
    const this_arg: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const result = z.lastElementChild(this_arg);
    if (result) |elem| { return DOMBridge.wrapElement(ctx, elem) catch w.EXCEPTION; } else { return w.NULL; }
}

// Property Getter for className
pub fn js_get_className(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return ctx.throwTypeError("Object is not an HTMLElement");
    const this_arg: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const result = z.className(this_arg);
    return ctx.newString(result);
}

// Boolean Getter for disabled
pub fn js_get_disabled(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);

    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const this_arg: *z.HTMLElement = @ptrCast(@alignCast(ptr));

    const is_present = z.hasAttribute(this_arg, "disabled");
    return ctx.newBool(is_present);
}

// Boolean Setter for disabled
pub fn js_set_disabled(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);

    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const this_arg: *z.HTMLElement = @ptrCast(@alignCast(ptr));

    // Convert JS value to boolean
    const val = qjs.JS_ToBool(ctx_ptr, argv[0]) != 0;

    if (val) {
        z.setAttribute(this_arg, "disabled", "") catch return w.EXCEPTION;
    } else {
        z.removeAttribute(this_arg, "disabled") catch return w.EXCEPTION;
    }
    return w.UNDEFINED;
}

// Boolean Getter for hidden
pub fn js_get_hidden(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);

    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const this_arg: *z.HTMLElement = @ptrCast(@alignCast(ptr));

    const is_present = z.hasAttribute(this_arg, "hidden");
    return ctx.newBool(is_present);
}

// Boolean Setter for hidden
pub fn js_set_hidden(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);

    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const this_arg: *z.HTMLElement = @ptrCast(@alignCast(ptr));

    // Convert JS value to boolean
    const val = qjs.JS_ToBool(ctx_ptr, argv[0]) != 0;

    if (val) {
        z.setAttribute(this_arg, "hidden", "") catch return w.EXCEPTION;
    } else {
        z.removeAttribute(this_arg, "hidden") catch return w.EXCEPTION;
    }
    return w.UNDEFINED;
}

// Boolean Getter for checked
pub fn js_get_checked(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);

    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const this_arg: *z.HTMLElement = @ptrCast(@alignCast(ptr));

    const is_present = z.hasAttribute(this_arg, "checked");
    return ctx.newBool(is_present);
}

// Boolean Setter for checked
pub fn js_set_checked(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);

    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const this_arg: *z.HTMLElement = @ptrCast(@alignCast(ptr));

    // Convert JS value to boolean
    const val = qjs.JS_ToBool(ctx_ptr, argv[0]) != 0;

    if (val) {
        z.setAttribute(this_arg, "checked", "") catch return w.EXCEPTION;
    } else {
        z.removeAttribute(this_arg, "checked") catch return w.EXCEPTION;
    }
    return w.UNDEFINED;
}

// Reflected String Getter for id -> id
pub fn js_get_id(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);

    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const this_arg: *z.HTMLElement = @ptrCast(@alignCast(ptr));

    // Call getAttribute (returns allocated !?[]u8)
    const val_opt = z.getAttribute(rc.allocator, this_arg, "id") catch return w.EXCEPTION;
    if (val_opt) |val| {
        defer rc.allocator.free(val);
        return ctx.newString(val);
    }
    // Reflected attributes usually return empty string if missing (not null)
    return ctx.newString("");
}

// Reflected String Setter for id -> id
pub fn js_set_id(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);

    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const this_arg: *z.HTMLElement = @ptrCast(@alignCast(ptr));

    const val_str = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(val_str);

    z.setAttribute(this_arg, "id", val_str) catch return w.EXCEPTION;
    return w.UNDEFINED;
}

// Reflected String Getter for title -> title
pub fn js_get_title(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);

    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const this_arg: *z.HTMLElement = @ptrCast(@alignCast(ptr));

    // Call getAttribute (returns allocated !?[]u8)
    const val_opt = z.getAttribute(rc.allocator, this_arg, "title") catch return w.EXCEPTION;
    if (val_opt) |val| {
        defer rc.allocator.free(val);
        return ctx.newString(val);
    }
    // Reflected attributes usually return empty string if missing (not null)
    return ctx.newString("");
}

// Reflected String Setter for title -> title
pub fn js_set_title(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);

    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const this_arg: *z.HTMLElement = @ptrCast(@alignCast(ptr));

    const val_str = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(val_str);

    z.setAttribute(this_arg, "title", val_str) catch return w.EXCEPTION;
    return w.UNDEFINED;
}

// Reflected String Getter for lang -> lang
pub fn js_get_lang(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);

    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const this_arg: *z.HTMLElement = @ptrCast(@alignCast(ptr));

    // Call getAttribute (returns allocated !?[]u8)
    const val_opt = z.getAttribute(rc.allocator, this_arg, "lang") catch return w.EXCEPTION;
    if (val_opt) |val| {
        defer rc.allocator.free(val);
        return ctx.newString(val);
    }
    // Reflected attributes usually return empty string if missing (not null)
    return ctx.newString("");
}

// Reflected String Setter for lang -> lang
pub fn js_set_lang(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);

    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const this_arg: *z.HTMLElement = @ptrCast(@alignCast(ptr));

    const val_str = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(val_str);

    z.setAttribute(this_arg, "lang", val_str) catch return w.EXCEPTION;
    return w.UNDEFINED;
}

// Reflected String Getter for dir -> dir
pub fn js_get_dir(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);

    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const this_arg: *z.HTMLElement = @ptrCast(@alignCast(ptr));

    // Call getAttribute (returns allocated !?[]u8)
    const val_opt = z.getAttribute(rc.allocator, this_arg, "dir") catch return w.EXCEPTION;
    if (val_opt) |val| {
        defer rc.allocator.free(val);
        return ctx.newString(val);
    }
    // Reflected attributes usually return empty string if missing (not null)
    return ctx.newString("");
}

// Reflected String Setter for dir -> dir
pub fn js_set_dir(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);

    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const this_arg: *z.HTMLElement = @ptrCast(@alignCast(ptr));

    const val_str = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(val_str);

    z.setAttribute(this_arg, "dir", val_str) catch return w.EXCEPTION;
    return w.UNDEFINED;
}

// Reflected String Getter for role -> role
pub fn js_get_role(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);

    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const this_arg: *z.HTMLElement = @ptrCast(@alignCast(ptr));

    // Call getAttribute (returns allocated !?[]u8)
    const val_opt = z.getAttribute(rc.allocator, this_arg, "role") catch return w.EXCEPTION;
    if (val_opt) |val| {
        defer rc.allocator.free(val);
        return ctx.newString(val);
    }
    // Reflected attributes usually return empty string if missing (not null)
    return ctx.newString("");
}

// Reflected String Setter for role -> role
pub fn js_set_role(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);

    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const this_arg: *z.HTMLElement = @ptrCast(@alignCast(ptr));

    const val_str = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(val_str);

    z.setAttribute(this_arg, "role", val_str) catch return w.EXCEPTION;
    return w.UNDEFINED;
}

// Reflected String Getter for nonce -> nonce
pub fn js_get_nonce(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);

    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const this_arg: *z.HTMLElement = @ptrCast(@alignCast(ptr));

    // Call getAttribute (returns allocated !?[]u8)
    const val_opt = z.getAttribute(rc.allocator, this_arg, "nonce") catch return w.EXCEPTION;
    if (val_opt) |val| {
        defer rc.allocator.free(val);
        return ctx.newString(val);
    }
    // Reflected attributes usually return empty string if missing (not null)
    return ctx.newString("");
}

// Reflected String Setter for nonce -> nonce
pub fn js_set_nonce(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);

    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const this_arg: *z.HTMLElement = @ptrCast(@alignCast(ptr));

    const val_str = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(val_str);

    z.setAttribute(this_arg, "nonce", val_str) catch return w.EXCEPTION;
    return w.UNDEFINED;
}

pub fn installDocumentBindings(ctx: ?*qjs.JSContext, proto: qjs.JSValue) void {
    _ = qjs.JS_SetPropertyStr(ctx, proto, "parseHTML", qjs.JS_NewCFunction(ctx, js_parseHTML, "parseHTML", 1));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "documentRoot", qjs.JS_NewCFunction(ctx, js_documentRoot, "documentRoot", 0));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "ownerDocument", qjs.JS_NewCFunction(ctx, js_ownerDocument, "ownerDocument", 0));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "createElement", qjs.JS_NewCFunction(ctx, js_createElement, "createElement", 1));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "createTextNode", qjs.JS_NewCFunction(ctx, js_createTextNode, "createTextNode", 1));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "getElementById", qjs.JS_NewCFunction(ctx, js_getElementById, "getElementById", 1));
    {
        const atom = qjs.JS_NewAtom(ctx, "body");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_body, "get_body", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
}

pub fn installNodeBindings(ctx: ?*qjs.JSContext, proto: qjs.JSValue) void {
    _ = qjs.JS_SetPropertyStr(ctx, proto, "addEventListener", qjs.JS_NewCFunction(ctx, js_addEventListener, "addEventListener", 2));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "removeEventListener", qjs.JS_NewCFunction(ctx, js_removeEventListener, "removeEventListener", 2));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "dispatchEvent", qjs.JS_NewCFunction(ctx, js_dispatchEvent, "dispatchEvent", 1));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "cloneNode", qjs.JS_NewCFunction(ctx, js_cloneNode, "cloneNode", 1));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "appendChild", qjs.JS_NewCFunction(ctx, js_appendChild, "appendChild", 1));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "insertBefore", qjs.JS_NewCFunction(ctx, js_insertBefore, "insertBefore", 1));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "parentNode", qjs.JS_NewCFunction(ctx, js_parentNode, "parentNode", 0));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "remove", qjs.JS_NewCFunction(ctx, js_remove, "remove", 0));
    {
        const atom = qjs.JS_NewAtom(ctx, "textContent");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_textContent, "get_textContent", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = qjs.JS_NewCFunction2(ctx, js_set_textContent, "set_textContent", 1, qjs.JS_CFUNC_generic, 0);
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "nodeValue");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_nodeValue, "get_nodeValue", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = qjs.JS_NewCFunction2(ctx, js_set_nodeValue, "set_nodeValue", 1, qjs.JS_CFUNC_generic, 0);
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "innerText");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_innerText, "get_innerText", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = qjs.JS_NewCFunction2(ctx, js_set_innerText, "set_innerText", 1, qjs.JS_CFUNC_generic, 0);
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "nextSibling");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_nextSibling, "get_nextSibling", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "previousSibling");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_previousSibling, "get_previousSibling", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "firstChild");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_firstChild, "get_firstChild", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "lastChild");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_lastChild, "get_lastChild", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "firstElementChild");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_firstElementChild, "get_firstElementChild", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
}

pub fn installElementBindings(ctx: ?*qjs.JSContext, proto: qjs.JSValue) void {
    _ = qjs.JS_SetPropertyStr(ctx, proto, "setAttribute", qjs.JS_NewCFunction(ctx, js_setAttribute, "setAttribute", 2));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "getAttribute", qjs.JS_NewCFunction(ctx, js_getAttribute, "getAttribute", 1));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "removeAttribute", qjs.JS_NewCFunction(ctx, js_removeAttribute, "removeAttribute", 1));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "setHTML", qjs.JS_NewCFunction(ctx, js_setHTML, "setHTML", 1));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "getHTML", qjs.JS_NewCFunction(ctx, js_getHTML, "getHTML", 0));
    {
        const atom = qjs.JS_NewAtom(ctx, "innerHTML");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_innerHTML, "get_innerHTML", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = qjs.JS_NewCFunction2(ctx, js_set_innerHTML, "set_innerHTML", 1, qjs.JS_CFUNC_generic, 0);
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "content");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_content, "get_content", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "nextElementSibling");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_nextElementSibling, "get_nextElementSibling", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "lastElementChild");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_lastElementChild, "get_lastElementChild", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "className");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_className, "get_className", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "disabled");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_disabled, "get_disabled", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "hidden");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_hidden, "get_hidden", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "checked");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_checked, "get_checked", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "id");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_id, "get_id", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "title");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_title, "get_title", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "lang");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_lang, "get_lang", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "dir");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_dir, "get_dir", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "role");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_role, "get_role", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "nonce");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_nonce, "get_nonce", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
}

pub fn installDOMParserBindings(ctx: ?*qjs.JSContext, proto: qjs.JSValue) void {
    _ = qjs.JS_SetPropertyStr(ctx, proto, "parseFromString", qjs.JS_NewCFunction(ctx, js_parseFromString, "parseFromString", 1));
}

pub fn installEventBindings(ctx: ?*qjs.JSContext, proto: qjs.JSValue) void {
    {
        const atom = qjs.JS_NewAtom(ctx, "type");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_type, "get_type", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "bubbles");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_bubbles, "get_bubbles", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "target");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_target, "get_target", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "currentTarget");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_currentTarget, "get_currentTarget", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    _ = qjs.JS_SetPropertyStr(ctx, proto, "stopPropagation", qjs.JS_NewCFunction(ctx, js_stopPropagation, "stopPropagation", 0));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "preventDefault", qjs.JS_NewCFunction(ctx, js_preventDefault, "preventDefault", 0));
}
