// THIS FILE IS AUTO-GENERATED BY tools/gen_bindings.zig
// DO NOT EDIT MANUALLY

const std = @import("std");
const z = @import("root.zig");
const w = @import("wrapper.zig");
const qjs = z.qjs;
const DOMBridge = @import("dom_bridge.zig").DOMBridge;
const RuntimeContext = @import("runtime_context.zig").RuntimeContext;

/// Generated wrapper for z.addEventListener
pub fn js_addEventListener(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 1) return w.EXCEPTION;
    const arg0 = ctx;
    const arg1: *DOMBridge = @ptrCast(@alignCast(rc.dom_bridge.?));
    const node_ptr2 = qjs.JS_GetOpaque(this_val, rc.classes.dom_node);
    if (node_ptr2 == null) return w.EXCEPTION;
    const arg2: *z.DomNode = @ptrCast(@alignCast(node_ptr2));
    const arg3 = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(arg3);
    const arg4 = argv[1];
    // Call native Zig function
    z.addEventListener(arg0, arg1, arg2, arg3, arg4) catch return w.EXCEPTION;

    return w.UNDEFINED;
}

/// Generated wrapper for z.dispatchEvent
pub fn js_dispatchEvent(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 1) return w.EXCEPTION;
    const arg0 = ctx;
    const arg1: *DOMBridge = @ptrCast(@alignCast(rc.dom_bridge.?));
    const node_ptr2 = qjs.JS_GetOpaque(this_val, rc.classes.dom_node);
    if (node_ptr2 == null) return w.EXCEPTION;
    const arg2: *z.DomNode = @ptrCast(@alignCast(node_ptr2));
    const arg3 = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(arg3);
    // Call native Zig function
    z.dispatchEvent(arg0, arg1, arg2, arg3) catch return w.EXCEPTION;

    return w.UNDEFINED;
}

/// Generated wrapper for z.createElement
pub fn js_createElement(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 1) return w.EXCEPTION;
    _ = this_val;
    const global0 = ctx.getGlobalObject();
    defer ctx.freeValue(global0);
    const doc_obj0 = ctx.getPropertyStr(global0, "document");
    defer ctx.freeValue(doc_obj0);
    const native_doc0 = ctx.getPropertyStr(doc_obj0, "_native_doc");
    defer ctx.freeValue(native_doc0);
    const doc_ptr0 = qjs.JS_GetOpaque(native_doc0, rc.classes.dom_node);
    if (doc_ptr0 == null) return w.EXCEPTION;
    const arg0: *z.HTMLDocument = @ptrCast(@alignCast(doc_ptr0));
    const arg1 = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(arg1);
    // Call native Zig function
    const result = z.createElement(arg0, arg1) catch return w.EXCEPTION;

    return DOMBridge.wrapElement(ctx, result) catch w.EXCEPTION;
}

/// Generated wrapper for z.documentRoot
pub fn js_documentRoot(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    _ = argc;
    _ = argv;
    _ = this_val;
    const global0 = ctx.getGlobalObject();
    defer ctx.freeValue(global0);
    const doc_obj0 = ctx.getPropertyStr(global0, "document");
    defer ctx.freeValue(doc_obj0);
    const native_doc0 = ctx.getPropertyStr(doc_obj0, "_native_doc");
    defer ctx.freeValue(native_doc0);
    const doc_ptr0 = qjs.JS_GetOpaque(native_doc0, rc.classes.dom_node);
    if (doc_ptr0 == null) return w.EXCEPTION;
    const arg0: *z.HTMLDocument = @ptrCast(@alignCast(doc_ptr0));
    // Call native Zig function
    const result = z.documentRoot(arg0);

    if (result) |node| {
        return DOMBridge.wrapNode(ctx, node) catch w.EXCEPTION;
    } else {
        return w.NULL;
    }
}

/// Generated wrapper for z.bodyElement
pub fn js_bodyElement(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    _ = argc;
    _ = argv;
    _ = this_val;
    const global0 = ctx.getGlobalObject();
    defer ctx.freeValue(global0);
    const doc_obj0 = ctx.getPropertyStr(global0, "document");
    defer ctx.freeValue(doc_obj0);
    const native_doc0 = ctx.getPropertyStr(doc_obj0, "_native_doc");
    defer ctx.freeValue(native_doc0);
    const doc_ptr0 = qjs.JS_GetOpaque(native_doc0, rc.classes.dom_node);
    if (doc_ptr0 == null) return w.EXCEPTION;
    const arg0: *z.HTMLDocument = @ptrCast(@alignCast(doc_ptr0));
    // Call native Zig function
    const result = z.bodyElement(arg0);

    if (result) |elem| {
        return DOMBridge.wrapElement(ctx, elem) catch w.EXCEPTION;
    } else {
        return w.NULL;
    }
}

/// Generated wrapper for z.ownerDocument
pub fn js_ownerDocument(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    _ = argc;
    _ = argv;
    const node_ptr0 = qjs.JS_GetOpaque(this_val, rc.classes.dom_node);
    if (node_ptr0 == null) return w.EXCEPTION;
    const arg0: *z.DomNode = @ptrCast(@alignCast(node_ptr0));
    // Call native Zig function
    const result = z.ownerDocument(arg0);

    const doc_obj = qjs.JS_NewObjectClass(ctx_ptr, @intCast(rc.classes.dom_node));
    _ = qjs.JS_SetOpaque(doc_obj, @ptrCast(result));
    return doc_obj;
}

/// Generated wrapper for z.createTextNode
pub fn js_createTextNode(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 1) return w.EXCEPTION;
    _ = this_val;
    const global0 = ctx.getGlobalObject();
    defer ctx.freeValue(global0);
    const doc_obj0 = ctx.getPropertyStr(global0, "document");
    defer ctx.freeValue(doc_obj0);
    const native_doc0 = ctx.getPropertyStr(doc_obj0, "_native_doc");
    defer ctx.freeValue(native_doc0);
    const doc_ptr0 = qjs.JS_GetOpaque(native_doc0, rc.classes.dom_node);
    if (doc_ptr0 == null) return w.EXCEPTION;
    const arg0: *z.HTMLDocument = @ptrCast(@alignCast(doc_ptr0));
    const arg1 = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(arg1);
    // Call native Zig function
    const result = z.createTextNode(arg0, arg1) catch return w.EXCEPTION;

    return DOMBridge.wrapNode(ctx, result) catch w.EXCEPTION;
}

/// Generated wrapper for z.getElementById
pub fn js_getElementById(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 1) return w.EXCEPTION;
    _ = this_val;
    const global0 = ctx.getGlobalObject();
    defer ctx.freeValue(global0);
    const doc_obj0 = ctx.getPropertyStr(global0, "document");
    defer ctx.freeValue(doc_obj0);
    const native_doc0 = ctx.getPropertyStr(doc_obj0, "_native_doc");
    defer ctx.freeValue(native_doc0);
    const doc_ptr0 = qjs.JS_GetOpaque(native_doc0, rc.classes.dom_node);
    if (doc_ptr0 == null) return w.EXCEPTION;
    const doc0: *z.HTMLDocument = @ptrCast(@alignCast(doc_ptr0));
    const root0 = z.documentRoot(doc0);
    if (root0 == null) return w.EXCEPTION;
    const arg0 = root0.?;
    const arg1 = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(arg1);
    // Call native Zig function
    const result = z.getElementById(arg0, arg1);

    if (result) |elem| {
        return DOMBridge.wrapElement(ctx, elem) catch w.EXCEPTION;
    } else {
        return w.NULL;
    }
}

/// Generated wrapper for z.appendChild
pub fn js_appendChild(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 1) return w.EXCEPTION;
    const node_ptr0 = qjs.JS_GetOpaque(this_val, rc.classes.dom_node);
    if (node_ptr0 == null) return w.EXCEPTION;
    const arg0: *z.DomNode = @ptrCast(@alignCast(node_ptr0));
    const node_arg_ptr1 = qjs.JS_GetOpaque(argv[0], rc.classes.dom_node);
    if (node_arg_ptr1 == null) return ctx.throwTypeError("Argument 0 must be a DOM Node");
    const arg1: *z.DomNode = @ptrCast(@alignCast(node_arg_ptr1));
    // Call native Zig function
    z.appendChild(arg0, arg1);

    return w.UNDEFINED;
}

/// Generated wrapper for z.firstChild
pub fn js_firstChild(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    _ = argc;
    _ = argv;
    const node_ptr0 = qjs.JS_GetOpaque(this_val, rc.classes.dom_node);
    if (node_ptr0 == null) return w.EXCEPTION;
    const arg0: *z.DomNode = @ptrCast(@alignCast(node_ptr0));
    // Call native Zig function
    const result = z.firstChild(arg0);

    if (result) |node| {
        return DOMBridge.wrapNode(ctx, node) catch w.EXCEPTION;
    } else {
        return w.NULL;
    }
}

/// Generated wrapper for z.parentNode
pub fn js_parentNode(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    _ = argc;
    _ = argv;
    const node_ptr0 = qjs.JS_GetOpaque(this_val, rc.classes.dom_node);
    if (node_ptr0 == null) return w.EXCEPTION;
    const arg0: *z.DomNode = @ptrCast(@alignCast(node_ptr0));
    // Call native Zig function
    const result = z.parentNode(arg0);

    if (result) |node| {
        return DOMBridge.wrapNode(ctx, node) catch w.EXCEPTION;
    } else {
        return w.NULL;
    }
}

/// Generated wrapper for z.removeNode
pub fn js_remove(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    _ = argc;
    _ = argv;
    const node_ptr0 = qjs.JS_GetOpaque(this_val, rc.classes.dom_node);
    if (node_ptr0 == null) return w.EXCEPTION;
    const arg0: *z.DomNode = @ptrCast(@alignCast(node_ptr0));
    // Call native Zig function
    z.removeNode(arg0);

    return w.UNDEFINED;
}

/// Generated wrapper for z.setAttribute
pub fn js_setAttribute(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 2) return w.EXCEPTION;
    const elem_ptr0 = qjs.JS_GetOpaque(this_val, rc.classes.dom_node);
    if (elem_ptr0 == null) return w.EXCEPTION;
    const arg0: *z.HTMLElement = @ptrCast(@alignCast(elem_ptr0));
    const arg1 = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(arg1);
    const arg2 = ctx.toZString(argv[1]) catch return w.EXCEPTION;
    defer ctx.freeZString(arg2);
    // Call native Zig function
    _ = z.setAttribute(arg0, arg1, arg2);

    return w.UNDEFINED;
}

/// Generated wrapper for z.getAttribute_zc
pub fn js_getAttribute(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 1) return w.EXCEPTION;
    const elem_ptr0 = qjs.JS_GetOpaque(this_val, rc.classes.dom_node);
    if (elem_ptr0 == null) return w.EXCEPTION;
    const arg0: *z.HTMLElement = @ptrCast(@alignCast(elem_ptr0));
    const arg1 = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(arg1);
    // Call native Zig function
    const result = z.getAttribute_zc(arg0, arg1);

    if (result) |str| {
        return ctx.newString(str);
    } else {
        return w.NULL;
    }
}

/// Generated wrapper for z.removeAttribute
pub fn js_removeAttribute(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 1) return w.EXCEPTION;
    const elem_ptr0 = qjs.JS_GetOpaque(this_val, rc.classes.dom_node);
    if (elem_ptr0 == null) return w.EXCEPTION;
    const arg0: *z.HTMLElement = @ptrCast(@alignCast(elem_ptr0));
    const arg1 = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(arg1);
    // Call native Zig function
    z.removeAttribute(arg0, arg1) catch return w.EXCEPTION;

    return w.UNDEFINED;
}

/// Generated wrapper for z.textContent_zc
pub fn js_textContent(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    _ = argc;
    _ = argv;
    const node_ptr0 = qjs.JS_GetOpaque(this_val, rc.classes.dom_node);
    if (node_ptr0 == null) return w.EXCEPTION;
    const arg0: *z.DomNode = @ptrCast(@alignCast(node_ptr0));
    // Call native Zig function
    const result = z.textContent_zc(arg0);

    return ctx.newString(result);
}

/// Generated wrapper for z.setContentAsText
pub fn js_setContentAsText(
    ctx_ptr: ?*qjs.JSContext,
    this_val: qjs.JSValue,
    argc: c_int,
    argv: [*c]qjs.JSValue,
) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 1) return w.EXCEPTION;
    const node_ptr0 = qjs.JS_GetOpaque(this_val, rc.classes.dom_node);
    if (node_ptr0 == null) return w.EXCEPTION;
    const arg0: *z.DomNode = @ptrCast(@alignCast(node_ptr0));
    const arg1 = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(arg1);
    // Call native Zig function
    z.setContentAsText(arg0, arg1) catch return w.EXCEPTION;

    return w.UNDEFINED;
}

// Property Getter for innerHTML
pub fn js_get_innerHTML(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc;
    _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.dom_node);
    if (ptr == null) return w.EXCEPTION;
    const this_arg: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const result = z.innerHTML(rc.allocator, this_arg) catch return w.EXCEPTION;
    defer rc.allocator.free(result);
    return ctx.newString(result);
}

// Property Setter for innerHTML
pub fn js_set_innerHTML(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.dom_node);
    if (ptr == null) return w.EXCEPTION;
    const this_arg: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const val = argv[0];
    const val_str = ctx.toZString(val) catch return w.EXCEPTION;
    defer ctx.freeZString(val_str);
    _ = z.setInnerHTML(this_arg, val_str) catch return w.EXCEPTION;
    return w.UNDEFINED;
}

// Install static bindings (document-level factories)
pub fn installStaticBindings(ctx: ?*qjs.JSContext, doc_obj: qjs.JSValue) void {
    _ = qjs.JS_SetPropertyStr(ctx, doc_obj, "createElement", qjs.JS_NewCFunction(ctx, js_createElement, "createElement", 1));
    _ = qjs.JS_SetPropertyStr(ctx, doc_obj, "documentRoot", qjs.JS_NewCFunction(ctx, js_documentRoot, "documentRoot", 0));
    _ = qjs.JS_SetPropertyStr(ctx, doc_obj, "bodyElement", qjs.JS_NewCFunction(ctx, js_bodyElement, "bodyElement", 0));
    _ = qjs.JS_SetPropertyStr(ctx, doc_obj, "ownerDocument", qjs.JS_NewCFunction(ctx, js_ownerDocument, "ownerDocument", 0));
    _ = qjs.JS_SetPropertyStr(ctx, doc_obj, "createTextNode", qjs.JS_NewCFunction(ctx, js_createTextNode, "createTextNode", 1));
    _ = qjs.JS_SetPropertyStr(ctx, doc_obj, "getElementById", qjs.JS_NewCFunction(ctx, js_getElementById, "getElementById", 1));
}

// Install method bindings (shared via prototype)
pub fn installMethodBindings(ctx: ?*qjs.JSContext, proto: qjs.JSValue) void {
    _ = qjs.JS_SetPropertyStr(ctx, proto, "addEventListener", qjs.JS_NewCFunction(ctx, js_addEventListener, "addEventListener", 1));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "dispatchEvent", qjs.JS_NewCFunction(ctx, js_dispatchEvent, "dispatchEvent", 1));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "appendChild", qjs.JS_NewCFunction(ctx, js_appendChild, "appendChild", 1));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "firstChild", qjs.JS_NewCFunction(ctx, js_firstChild, "firstChild", 0));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "parentNode", qjs.JS_NewCFunction(ctx, js_parentNode, "parentNode", 0));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "remove", qjs.JS_NewCFunction(ctx, js_remove, "remove", 0));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "setAttribute", qjs.JS_NewCFunction(ctx, js_setAttribute, "setAttribute", 2));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "getAttribute", qjs.JS_NewCFunction(ctx, js_getAttribute, "getAttribute", 1));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "removeAttribute", qjs.JS_NewCFunction(ctx, js_removeAttribute, "removeAttribute", 1));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "textContent", qjs.JS_NewCFunction(ctx, js_textContent, "textContent", 0));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "setContentAsText", qjs.JS_NewCFunction(ctx, js_setContentAsText, "setContentAsText", 1));
    {
        const atom = qjs.JS_NewAtom(ctx, "innerHTML");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_innerHTML, "get_innerHTML", 0, qjs.JS_CFUNC_getter, 0);
        const set_fn = qjs.JS_NewCFunction2(ctx, js_set_innerHTML, "set_innerHTML", 1, qjs.JS_CFUNC_setter, 0);
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
}
