// THIS FILE IS AUTO-GENERATED BY tools/template_gen.zig
// DO NOT EDIT MANUALLY

const std = @import("std");
const z = @import("root.zig");
const w = @import("wrapper.zig");
const qjs = z.qjs;
const DOMBridge = @import("dom_bridge.zig").DOMBridge;
const RuntimeContext = @import("runtime_context.zig").RuntimeContext;
const js_CSSStyleDeclaration = @import("js_CSSStyleDeclaration.zig");
/// Generated wrapper for z.parseHTML
pub fn js_parseHTML(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = this_val;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 1) return w.EXCEPTION;
    const arg_str = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(arg_str);
    const result = z.parseHTML(rc.allocator, arg_str) catch |err| {
        if (@errorReturnTrace()) |trace| std.debug.dumpStackTrace(trace.*);
        std.debug.print("JS Binding Error: {}\n", .{err});
        return ctx.throwTypeError("Native Zig Error");
    };
    const doc_obj = qjs.JS_NewObjectClass(ctx_ptr, @intCast(rc.classes.owned_document));
    _ = qjs.JS_SetOpaque(doc_obj, @ptrCast(result));
    return doc_obj;
}
/// Generated wrapper for z.documentRoot
pub fn js_documentRoot(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv; _ = this_val;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const global = ctx.getGlobalObject();
    defer ctx.freeValue(global);
    const doc_obj = ctx.getPropertyStr(global, "document");
    defer ctx.freeValue(doc_obj);
    const native_doc = ctx.getPropertyStr(doc_obj, "_native_doc");
    defer ctx.freeValue(native_doc);
    const doc_ptr = qjs.JS_GetOpaque(native_doc, rc.classes.document);
    if (doc_ptr == null) return w.EXCEPTION;
    const doc: *z.HTMLDocument = @ptrCast(@alignCast(doc_ptr));
    const result = z.documentRoot(doc);
    if (result) |n| return DOMBridge.wrapNode(ctx, n) catch w.EXCEPTION;
    return w.NULL;
}
/// Generated wrapper for z.ownerDocument
pub fn js_ownerDocument(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const node = DOMBridge.unwrapNode(ctx, this_val) orelse return ctx.throwTypeError("'this' is not a Node (or unwrap failed)");
    const result = z.ownerDocument(node);
    const doc_obj = qjs.JS_NewObjectClass(ctx_ptr, @intCast(rc.classes.document));
    _ = qjs.JS_SetOpaque(doc_obj, @ptrCast(result));
    return doc_obj;
}
/// Generated wrapper for z.createElement
pub fn js_createElement(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 1) return w.EXCEPTION;
    const doc: *z.HTMLDocument = blk: {
        if (qjs.JS_GetOpaque(this_val, rc.classes.document)) |ptr| break :blk @ptrCast(@alignCast(ptr));
        if (qjs.JS_GetOpaque(this_val, rc.classes.owned_document)) |ptr| break :blk @ptrCast(@alignCast(ptr));
        return ctx.throwTypeError("Method called on object that is not a Document");
    };
    const arg_str = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(arg_str);
    const result = z.createElement(doc, arg_str) catch |err| {
        if (@errorReturnTrace()) |trace| std.debug.dumpStackTrace(trace.*);
        std.debug.print("JS Binding Error: {}\n", .{err});
        return ctx.throwTypeError("Native Zig Error");
    };
    return DOMBridge.wrapElement(ctx, result) catch w.EXCEPTION;
}
/// Generated wrapper for z.createTextNode
pub fn js_createTextNode(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 1) return w.EXCEPTION;
    const doc: *z.HTMLDocument = blk: {
        if (qjs.JS_GetOpaque(this_val, rc.classes.document)) |ptr| break :blk @ptrCast(@alignCast(ptr));
        if (qjs.JS_GetOpaque(this_val, rc.classes.owned_document)) |ptr| break :blk @ptrCast(@alignCast(ptr));
        return ctx.throwTypeError("Method called on object that is not a Document");
    };
    const arg_str = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(arg_str);
    const result = z.createTextNode(doc, arg_str) catch |err| {
        if (@errorReturnTrace()) |trace| std.debug.dumpStackTrace(trace.*);
        std.debug.print("JS Binding Error: {}\n", .{err});
        return ctx.throwTypeError("Native Zig Error");
    };
    return DOMBridge.wrapNode(ctx, result) catch w.EXCEPTION;
}
/// Generated wrapper for z.getElementById
pub fn js_getElementById(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 1) return w.EXCEPTION;
    const doc: *z.HTMLDocument = blk: {
        if (qjs.JS_GetOpaque(this_val, rc.classes.document)) |ptr| break :blk @ptrCast(@alignCast(ptr));
        if (qjs.JS_GetOpaque(this_val, rc.classes.owned_document)) |ptr| break :blk @ptrCast(@alignCast(ptr));
        return ctx.throwTypeError("Method called on object that is not a Document");
    };
    const arg_str = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(arg_str);
    const result = z.getElementById(doc, arg_str);
    if (result) |el| return DOMBridge.wrapElement(ctx, el) catch w.EXCEPTION;
    return w.NULL;
}
/// Generated wrapper for z.DOMParser.parseFromString
pub fn js_parseFromString(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 1) return w.EXCEPTION;
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.dom_parser);
    if (ptr == null) return ctx.throwTypeError("Object is not a DOMParser");
    const parser: *z.DOMParser = @ptrCast(@alignCast(ptr));
    const arg_str = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(arg_str);
    const result = z.DOMParser.parseFromString(parser, arg_str) catch |err| {
        if (@errorReturnTrace()) |trace| std.debug.dumpStackTrace(trace.*);
        std.debug.print("JS Binding Error: {}\n", .{err});
        return ctx.throwTypeError("Native Zig Error");
    };
    const doc_obj = qjs.JS_NewObjectClass(ctx_ptr, @intCast(rc.classes.owned_document));
    _ = qjs.JS_SetOpaque(doc_obj, @ptrCast(result));
    return doc_obj;
}
// Property Getter for type
pub fn js_get_type(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.event);
    if (ptr == null) return ctx.throwTypeError("Object is not an Event");
    const ev: *z.events.DomEvent = @ptrCast(@alignCast(ptr));
    const result = z.events.getType(ev);
    return ctx.newString(result);
}
// Property Getter for bubbles
pub fn js_get_bubbles(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.event);
    if (ptr == null) return ctx.throwTypeError("Object is not an Event");
    const ev: *z.events.DomEvent = @ptrCast(@alignCast(ptr));
    const result = z.events.getBubbles(ev);
    return ctx.newBool(result);
}
// Property Getter for target
pub fn js_get_target(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.event);
    if (ptr == null) return ctx.throwTypeError("Object is not an Event");
    const ev: *z.events.DomEvent = @ptrCast(@alignCast(ptr));
    const result = z.events.getTarget(ev);
    if (result) |n| return DOMBridge.wrapNode(ctx, n) catch w.EXCEPTION;
    return w.NULL;
}
// Property Getter for currentTarget
pub fn js_get_currentTarget(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.event);
    if (ptr == null) return ctx.throwTypeError("Object is not an Event");
    const ev: *z.events.DomEvent = @ptrCast(@alignCast(ptr));
    const result = z.events.getCurrentTarget(ev);
    if (result) |n| return DOMBridge.wrapNode(ctx, n) catch w.EXCEPTION;
    return w.NULL;
}
/// Generated wrapper for z.events.stopPropagation
pub fn js_stopPropagation(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.event);
    if (ptr == null) return ctx.throwTypeError("Object is not an Event");
    const ev: *z.events.DomEvent = @ptrCast(@alignCast(ptr));
    z.events.stopPropagation(ev);
    return w.UNDEFINED;
}
/// Generated wrapper for z.events.preventDefault
pub fn js_preventDefault(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.event);
    if (ptr == null) return ctx.throwTypeError("Object is not an Event");
    const ev: *z.events.DomEvent = @ptrCast(@alignCast(ptr));
    z.events.preventDefault(ev);
    return w.UNDEFINED;
}
/// Generated wrapper for z.addEventListener
pub fn js_addEventListener(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 2) return w.EXCEPTION;
    const bridge: *DOMBridge = @ptrCast(@alignCast(rc.dom_bridge.?));
    const node = DOMBridge.unwrapNode(ctx, this_val) orelse return ctx.throwTypeError("'this' is not a Node");
    const event_str = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(event_str);
    const callback = argv[1];
    z.addEventListener(ctx, bridge, node, event_str, callback) catch |err| {
        if (@errorReturnTrace()) |trace| std.debug.dumpStackTrace(trace.*);
        std.debug.print("JS Binding Error: {}\n", .{err});
        return ctx.throwTypeError("Native Zig Error");
    };
    return w.UNDEFINED;
}
/// Generated wrapper for z.removeEventListener
pub fn js_removeEventListener(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 2) return w.EXCEPTION;
    const bridge: *DOMBridge = @ptrCast(@alignCast(rc.dom_bridge.?));
    const node = DOMBridge.unwrapNode(ctx, this_val) orelse return ctx.throwTypeError("'this' is not a Node");
    const event_str = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(event_str);
    const callback = argv[1];
    z.removeEventListener(ctx, bridge, node, event_str, callback) catch |err| {
        if (@errorReturnTrace()) |trace| std.debug.dumpStackTrace(trace.*);
        std.debug.print("JS Binding Error: {}\n", .{err});
        return ctx.throwTypeError("Native Zig Error");
    };
    return w.UNDEFINED;
}
/// Generated wrapper for z.dispatchEvent
pub fn js_dispatchEvent(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 1) return w.EXCEPTION;
    const bridge: *DOMBridge = @ptrCast(@alignCast(rc.dom_bridge.?));
    const node = DOMBridge.unwrapNode(ctx, this_val) orelse return ctx.throwTypeError("'this' is not a Node");
    const event_arg = argv[0];
    const result = z.dispatchEvent(ctx, bridge, node, event_arg) catch |err| {
        if (@errorReturnTrace()) |trace| std.debug.dumpStackTrace(trace.*);
        std.debug.print("JS Binding Error: {}\n", .{err});
        return ctx.throwTypeError("Native Zig Error");
    };
    return ctx.newBool(result);
}
/// Generated wrapper for z.cloneNode
pub fn js_cloneNode(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    if (argc < 1) return w.EXCEPTION;
    const node = DOMBridge.unwrapNode(ctx, this_val) orelse return ctx.throwTypeError("'this' is not a Node");
    const deep = qjs.JS_ToBool(ctx_ptr, argv[0]) != 0;
    const result = z.cloneNode(node, deep);
    if (result) |n| return DOMBridge.wrapNode(ctx, n) catch w.EXCEPTION;
    return w.NULL;
}
/// Generated wrapper for z.appendChild
pub fn js_appendChild(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    if (argc < 1) return w.EXCEPTION;
    const node = DOMBridge.unwrapNode(ctx, this_val) orelse return ctx.throwTypeError("'this' is not a Node");
    const child = DOMBridge.unwrapNode(ctx, argv[0]) orelse return ctx.throwTypeError("Argument must be a Node");
    z.appendChild(node, child);
    return w.UNDEFINED;
}
/// Generated wrapper for z.insertBefore
pub fn js_insertBefore(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    if (argc < 1) return w.EXCEPTION;
    const node = DOMBridge.unwrapNode(ctx, this_val) orelse return ctx.throwTypeError("'this' is not a Node");
    const child = DOMBridge.unwrapNode(ctx, argv[0]) orelse return ctx.throwTypeError("Argument must be a Node");
    z.insertBefore(node, child);
    return w.UNDEFINED;
}
/// Generated wrapper for z.parentNode
pub fn js_parentNode(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    _ = argc; _ = argv;
    const node = DOMBridge.unwrapNode(ctx, this_val) orelse return ctx.throwTypeError("'this' is not a Node");
    
    const result = z.parentNode(node);
    if (result) |n| return DOMBridge.wrapNode(ctx, n) catch w.EXCEPTION;
    return w.NULL;
}
/// Generated wrapper for z.removeNode
pub fn js_remove(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    _ = argc; _ = argv;
    const node = DOMBridge.unwrapNode(ctx, this_val) orelse return ctx.throwTypeError("'this' is not a Node");
    
    z.removeNode(node);
    return w.UNDEFINED;
}
/// Generated wrapper for z.setAttribute
pub fn js_setAttribute(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 2) return w.EXCEPTION;
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const el: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const arg1 = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(arg1);
    const arg2 = ctx.toZString(argv[1]) catch return w.EXCEPTION;
    defer ctx.freeZString(arg2);
    z.setAttribute(el, arg1, arg2) catch |err| {
        if (@errorReturnTrace()) |trace| std.debug.dumpStackTrace(trace.*);
        std.debug.print("JS Binding Error: {}\n", .{err});
        return ctx.throwTypeError("Native Zig Error");
    };
    return w.UNDEFINED;
}
/// Generated wrapper for z.getAttribute_zc
pub fn js_getAttribute(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 1) return w.EXCEPTION;
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const el: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const arg_str = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(arg_str);
    const result = z.getAttribute_zc(el, arg_str);
    if (result) |str| return ctx.newString(str);
    return w.NULL;
}
/// Generated wrapper for z.removeAttribute
pub fn js_removeAttribute(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 1) return w.EXCEPTION;
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const el: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const arg1 = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(arg1);
    z.removeAttribute(el, arg1) catch |err| {
        if (@errorReturnTrace()) |trace| std.debug.dumpStackTrace(trace.*);
        std.debug.print("JS Binding Error: {}\n", .{err});
        return ctx.throwTypeError("Native Zig Error");
    };
    return w.UNDEFINED;
}
/// Generated wrapper for z.setHTML
pub fn js_setHTML(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    if (argc < 1) return w.EXCEPTION;
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const el: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const arg_str = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(arg_str);
    z.setHTML(rc.allocator, el, arg_str) catch |err| {
        if (@errorReturnTrace()) |trace| std.debug.dumpStackTrace(trace.*);
        std.debug.print("JS Binding Error: {}\n", .{err});
        return ctx.throwTypeError("Native Zig Error");
    };
    return w.UNDEFINED;
}
/// Generated wrapper for z.getHTML
pub fn js_getHTML(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const el: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const result = z.getHTML(rc.allocator, el) catch |err| {
        if (@errorReturnTrace()) |trace| std.debug.dumpStackTrace(trace.*);
        std.debug.print("JS Binding Error: {}\n", .{err});
        return ctx.throwTypeError("Native Zig Error");
    };
    defer rc.allocator.free(result);
    return ctx.newString(result);
}
// Property Getter for body
pub fn js_get_body(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const doc: *z.HTMLDocument = blk: {
        if (qjs.JS_GetOpaque(this_val, rc.classes.document)) |ptr| break :blk @ptrCast(@alignCast(ptr));
        if (qjs.JS_GetOpaque(this_val, rc.classes.owned_document)) |ptr| break :blk @ptrCast(@alignCast(ptr));
        return ctx.throwTypeError("Method called on object that is not a Document");
    };
    const result = z.bodyElement(doc);
    if (result) |el| return DOMBridge.wrapElement(ctx, el) catch w.EXCEPTION;
    return w.NULL;
}
// Property Getter for textContent
pub fn js_get_textContent(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const node = DOMBridge.unwrapNode(ctx, this_val) orelse return w.EXCEPTION;
    const result = z.textContent_zc(node);
    return ctx.newString(result);
}
// Property Setter for textContent
pub fn js_set_textContent(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const node = DOMBridge.unwrapNode(ctx, this_val) orelse return ctx.throwTypeError("'this' is not a Node");
    const val_str = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(val_str);
    z.setContentAsText(node, val_str) catch |err| {
        std.debug.print("JS Setter Error (textContent): {}\n", .{err});
        return ctx.throwTypeError("Native Zig Error in Setter");
    };
    return w.UNDEFINED;
}
// Property Getter for nodeValue
pub fn js_get_nodeValue(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const node = DOMBridge.unwrapNode(ctx, this_val) orelse return w.EXCEPTION;
    const result = z.nodeValue_zc(node);
    return ctx.newString(result);
}
// Property Setter for nodeValue
pub fn js_set_nodeValue(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const node = DOMBridge.unwrapNode(ctx, this_val) orelse return ctx.throwTypeError("'this' is not a Node");
    const val_str = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(val_str);
    z.setNodeValue(node, val_str) catch |err| {
        std.debug.print("JS Setter Error (nodeValue): {}\n", .{err});
        return ctx.throwTypeError("Native Zig Error in Setter");
    };
    return w.UNDEFINED;
}
// Property Getter for innerText
pub fn js_get_innerText(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const node = DOMBridge.unwrapNode(ctx, this_val) orelse return w.EXCEPTION;
    const result = z.textContent_zc(node);
    return ctx.newString(result);
}
// Property Setter for innerText
pub fn js_set_innerText(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const node = DOMBridge.unwrapNode(ctx, this_val) orelse return ctx.throwTypeError("'this' is not a Node");
    const val_str = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(val_str);
    z.setContentAsText(node, val_str) catch |err| {
        std.debug.print("JS Setter Error (innerText): {}\n", .{err});
        return ctx.throwTypeError("Native Zig Error in Setter");
    };
    return w.UNDEFINED;
}
// Property Getter for innerHTML
pub fn js_get_innerHTML(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return ctx.throwTypeError("Object is not an HTMLElement");
    const el: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const result = z.innerHTML(rc.allocator, el) catch return w.EXCEPTION;
    defer rc.allocator.free(result);
    return ctx.newString(result);
}
// Property Setter for innerHTML
pub fn js_set_innerHTML(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return ctx.throwTypeError("Setter called on object that is not an HTMLElement");
    const el: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const val_str = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(val_str);
    z.setInnerHTML(el, val_str) catch |err| {
        std.debug.print("JS Setter Error (innerHTML): {}\n", .{err});
        return ctx.throwTypeError("Native Zig Error in Setter");
    };
    return w.UNDEFINED;
}
// Property Getter for content
pub fn js_get_content(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return ctx.throwTypeError("Object is not an HTMLElement");
    const el: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const result = z.getTemplateContentAsNode(el);
    if (result) |n| return DOMBridge.wrapNode(ctx, n) catch w.EXCEPTION;
    return w.NULL;
}
// Property Getter for nextSibling
pub fn js_get_nextSibling(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const node = DOMBridge.unwrapNode(ctx, this_val) orelse return w.EXCEPTION;
    const result = z.nextSibling(node);
    if (result) |n| return DOMBridge.wrapNode(ctx, n) catch w.EXCEPTION;
    return w.NULL;
}
// Property Getter for previousSibling
pub fn js_get_previousSibling(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const node = DOMBridge.unwrapNode(ctx, this_val) orelse return w.EXCEPTION;
    const result = z.previousSibling(node);
    if (result) |n| return DOMBridge.wrapNode(ctx, n) catch w.EXCEPTION;
    return w.NULL;
}
// Property Getter for firstChild
pub fn js_get_firstChild(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const node = DOMBridge.unwrapNode(ctx, this_val) orelse return w.EXCEPTION;
    const result = z.firstChild(node);
    if (result) |n| return DOMBridge.wrapNode(ctx, n) catch w.EXCEPTION;
    return w.NULL;
}
// Property Getter for lastChild
pub fn js_get_lastChild(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const node = DOMBridge.unwrapNode(ctx, this_val) orelse return w.EXCEPTION;
    const result = z.lastChild(node);
    if (result) |n| return DOMBridge.wrapNode(ctx, n) catch w.EXCEPTION;
    return w.NULL;
}
// Property Getter for firstElementChild
pub fn js_get_firstElementChild(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const node = DOMBridge.unwrapNode(ctx, this_val) orelse return w.EXCEPTION;
    const result = z.firstElementChild(node);
    if (result) |el| return DOMBridge.wrapElement(ctx, el) catch w.EXCEPTION;
    return w.NULL;
}
// Property Getter for nextElementSibling
pub fn js_get_nextElementSibling(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return ctx.throwTypeError("Object is not an HTMLElement");
    const el: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const result = z.nextElementSibling(el);
    if (result) |e| return DOMBridge.wrapElement(ctx, e) catch w.EXCEPTION;
    return w.NULL;
}
// Property Getter for lastElementChild
pub fn js_get_lastElementChild(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return ctx.throwTypeError("Object is not an HTMLElement");
    const el: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const result = z.lastElementChild(el);
    if (result) |e| return DOMBridge.wrapElement(ctx, e) catch w.EXCEPTION;
    return w.NULL;
}
// Property Getter for className
pub fn js_get_className(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return ctx.throwTypeError("Object is not an HTMLElement");
    const el: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const result = z.className(el);
    return ctx.newString(result);
}
// Boolean Getter for disabled
pub fn js_get_disabled(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const el: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    return ctx.newBool(z.hasAttribute(el, "disabled"));
}
// Boolean Setter for disabled
pub fn js_set_disabled(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const el: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const val = qjs.JS_ToBool(ctx_ptr, argv[0]) != 0;
    if (val) {
        z.setAttribute(el, "disabled", "") catch return w.EXCEPTION;
    } else {
        z.removeAttribute(el, "disabled") catch return w.EXCEPTION;
    }
    return w.UNDEFINED;
}
// Boolean Getter for hidden
pub fn js_get_hidden(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const el: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    return ctx.newBool(z.hasAttribute(el, "hidden"));
}
// Boolean Setter for hidden
pub fn js_set_hidden(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const el: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const val = qjs.JS_ToBool(ctx_ptr, argv[0]) != 0;
    if (val) {
        z.setAttribute(el, "hidden", "") catch return w.EXCEPTION;
    } else {
        z.removeAttribute(el, "hidden") catch return w.EXCEPTION;
    }
    return w.UNDEFINED;
}
// Boolean Getter for checked
pub fn js_get_checked(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const el: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    return ctx.newBool(z.hasAttribute(el, "checked"));
}
// Boolean Setter for checked
pub fn js_set_checked(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const el: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const val = qjs.JS_ToBool(ctx_ptr, argv[0]) != 0;
    if (val) {
        z.setAttribute(el, "checked", "") catch return w.EXCEPTION;
    } else {
        z.removeAttribute(el, "checked") catch return w.EXCEPTION;
    }
    return w.UNDEFINED;
}
// Reflected String Getter for id -> id
pub fn js_get_id(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const el: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const val_opt = z.getAttribute(rc.allocator, el, "id") catch return w.EXCEPTION;
    if (val_opt) |val| {
        defer rc.allocator.free(val);
        return ctx.newString(val);
    }
    return ctx.newString("");
}
// Reflected String Setter for id -> id
pub fn js_set_id(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const el: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const val_str = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(val_str);
    z.setAttribute(el, "id", val_str) catch return w.EXCEPTION;
    return w.UNDEFINED;
}
// Reflected String Getter for title -> title
pub fn js_get_title(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const el: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const val_opt = z.getAttribute(rc.allocator, el, "title") catch return w.EXCEPTION;
    if (val_opt) |val| {
        defer rc.allocator.free(val);
        return ctx.newString(val);
    }
    return ctx.newString("");
}
// Reflected String Setter for title -> title
pub fn js_set_title(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const el: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const val_str = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(val_str);
    z.setAttribute(el, "title", val_str) catch return w.EXCEPTION;
    return w.UNDEFINED;
}
// Reflected String Getter for lang -> lang
pub fn js_get_lang(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const el: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const val_opt = z.getAttribute(rc.allocator, el, "lang") catch return w.EXCEPTION;
    if (val_opt) |val| {
        defer rc.allocator.free(val);
        return ctx.newString(val);
    }
    return ctx.newString("");
}
// Reflected String Setter for lang -> lang
pub fn js_set_lang(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const el: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const val_str = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(val_str);
    z.setAttribute(el, "lang", val_str) catch return w.EXCEPTION;
    return w.UNDEFINED;
}
// Reflected String Getter for dir -> dir
pub fn js_get_dir(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const el: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const val_opt = z.getAttribute(rc.allocator, el, "dir") catch return w.EXCEPTION;
    if (val_opt) |val| {
        defer rc.allocator.free(val);
        return ctx.newString(val);
    }
    return ctx.newString("");
}
// Reflected String Setter for dir -> dir
pub fn js_set_dir(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const el: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const val_str = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(val_str);
    z.setAttribute(el, "dir", val_str) catch return w.EXCEPTION;
    return w.UNDEFINED;
}
// Reflected String Getter for role -> role
pub fn js_get_role(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const el: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const val_opt = z.getAttribute(rc.allocator, el, "role") catch return w.EXCEPTION;
    if (val_opt) |val| {
        defer rc.allocator.free(val);
        return ctx.newString(val);
    }
    return ctx.newString("");
}
// Reflected String Setter for role -> role
pub fn js_set_role(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const el: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const val_str = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(val_str);
    z.setAttribute(el, "role", val_str) catch return w.EXCEPTION;
    return w.UNDEFINED;
}
// Reflected String Getter for nonce -> nonce
pub fn js_get_nonce(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc; _ = argv;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const el: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const val_opt = z.getAttribute(rc.allocator, el, "nonce") catch return w.EXCEPTION;
    if (val_opt) |val| {
        defer rc.allocator.free(val);
        return ctx.newString(val);
    }
    return ctx.newString("");
}
// Reflected String Setter for nonce -> nonce
pub fn js_set_nonce(ctx_ptr: ?*qjs.JSContext, this_val: qjs.JSValue, argc: c_int, argv: [*c]qjs.JSValue) callconv(.c) qjs.JSValue {
    _ = argc;
    const ctx = w.Context{ .ptr = ctx_ptr };
    const rc = RuntimeContext.get(ctx);
    const ptr = qjs.JS_GetOpaque(this_val, rc.classes.html_element);
    if (ptr == null) return w.EXCEPTION;
    const el: *z.HTMLElement = @ptrCast(@alignCast(ptr));
    const val_str = ctx.toZString(argv[0]) catch return w.EXCEPTION;
    defer ctx.freeZString(val_str);
    z.setAttribute(el, "nonce", val_str) catch return w.EXCEPTION;
    return w.UNDEFINED;
}

pub fn installDocumentBindings(ctx: ?*qjs.JSContext, proto: qjs.JSValue) void {
    _ = qjs.JS_SetPropertyStr(ctx, proto, "parseHTML", qjs.JS_NewCFunction(ctx, js_parseHTML, "parseHTML", 1));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "documentRoot", qjs.JS_NewCFunction(ctx, js_documentRoot, "documentRoot", 0));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "ownerDocument", qjs.JS_NewCFunction(ctx, js_ownerDocument, "ownerDocument", 0));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "createElement", qjs.JS_NewCFunction(ctx, js_createElement, "createElement", 1));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "createTextNode", qjs.JS_NewCFunction(ctx, js_createTextNode, "createTextNode", 1));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "getElementById", qjs.JS_NewCFunction(ctx, js_getElementById, "getElementById", 1));
    {
        const atom = qjs.JS_NewAtom(ctx, "body");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_body, "get_body", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
}

pub fn installNodeBindings(ctx: ?*qjs.JSContext, proto: qjs.JSValue) void {
    _ = qjs.JS_SetPropertyStr(ctx, proto, "addEventListener", qjs.JS_NewCFunction(ctx, js_addEventListener, "addEventListener", 2));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "removeEventListener", qjs.JS_NewCFunction(ctx, js_removeEventListener, "removeEventListener", 2));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "dispatchEvent", qjs.JS_NewCFunction(ctx, js_dispatchEvent, "dispatchEvent", 1));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "cloneNode", qjs.JS_NewCFunction(ctx, js_cloneNode, "cloneNode", 1));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "appendChild", qjs.JS_NewCFunction(ctx, js_appendChild, "appendChild", 1));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "insertBefore", qjs.JS_NewCFunction(ctx, js_insertBefore, "insertBefore", 1));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "parentNode", qjs.JS_NewCFunction(ctx, js_parentNode, "parentNode", 0));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "remove", qjs.JS_NewCFunction(ctx, js_remove, "remove", 0));
    {
        const atom = qjs.JS_NewAtom(ctx, "textContent");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_textContent, "get_textContent", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = qjs.JS_NewCFunction2(ctx, js_set_textContent, "set_textContent", 1, qjs.JS_CFUNC_generic, 0);
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "nodeValue");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_nodeValue, "get_nodeValue", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = qjs.JS_NewCFunction2(ctx, js_set_nodeValue, "set_nodeValue", 1, qjs.JS_CFUNC_generic, 0);
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "innerText");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_innerText, "get_innerText", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = qjs.JS_NewCFunction2(ctx, js_set_innerText, "set_innerText", 1, qjs.JS_CFUNC_generic, 0);
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "nextSibling");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_nextSibling, "get_nextSibling", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "previousSibling");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_previousSibling, "get_previousSibling", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "firstChild");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_firstChild, "get_firstChild", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "lastChild");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_lastChild, "get_lastChild", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "firstElementChild");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_firstElementChild, "get_firstElementChild", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
}

pub fn installElementBindings(ctx: ?*qjs.JSContext, proto: qjs.JSValue) void {
    _ = qjs.JS_SetPropertyStr(ctx, proto, "setAttribute", qjs.JS_NewCFunction(ctx, js_setAttribute, "setAttribute", 2));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "getAttribute", qjs.JS_NewCFunction(ctx, js_getAttribute, "getAttribute", 1));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "removeAttribute", qjs.JS_NewCFunction(ctx, js_removeAttribute, "removeAttribute", 1));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "setHTML", qjs.JS_NewCFunction(ctx, js_setHTML, "setHTML", 1));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "getHTML", qjs.JS_NewCFunction(ctx, js_getHTML, "getHTML", 0));
    {
        const atom = qjs.JS_NewAtom(ctx, "innerHTML");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_innerHTML, "get_innerHTML", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = qjs.JS_NewCFunction2(ctx, js_set_innerHTML, "set_innerHTML", 1, qjs.JS_CFUNC_generic, 0);
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "content");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_content, "get_content", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "nextElementSibling");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_nextElementSibling, "get_nextElementSibling", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "lastElementChild");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_lastElementChild, "get_lastElementChild", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "className");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_className, "get_className", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "disabled");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_disabled, "get_disabled", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = qjs.JS_NewCFunction2(ctx, js_set_disabled, "set_disabled", 1, qjs.JS_CFUNC_generic, 0);
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "hidden");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_hidden, "get_hidden", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = qjs.JS_NewCFunction2(ctx, js_set_hidden, "set_hidden", 1, qjs.JS_CFUNC_generic, 0);
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "checked");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_checked, "get_checked", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = qjs.JS_NewCFunction2(ctx, js_set_checked, "set_checked", 1, qjs.JS_CFUNC_generic, 0);
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "id");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_id, "get_id", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = qjs.JS_NewCFunction2(ctx, js_set_id, "set_id", 1, qjs.JS_CFUNC_generic, 0);
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "title");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_title, "get_title", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = qjs.JS_NewCFunction2(ctx, js_set_title, "set_title", 1, qjs.JS_CFUNC_generic, 0);
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "lang");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_lang, "get_lang", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = qjs.JS_NewCFunction2(ctx, js_set_lang, "set_lang", 1, qjs.JS_CFUNC_generic, 0);
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "dir");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_dir, "get_dir", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = qjs.JS_NewCFunction2(ctx, js_set_dir, "set_dir", 1, qjs.JS_CFUNC_generic, 0);
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "role");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_role, "get_role", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = qjs.JS_NewCFunction2(ctx, js_set_role, "set_role", 1, qjs.JS_CFUNC_generic, 0);
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "nonce");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_nonce, "get_nonce", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = qjs.JS_NewCFunction2(ctx, js_set_nonce, "set_nonce", 1, qjs.JS_CFUNC_generic, 0);
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
}

pub fn installDOMParserBindings(ctx: ?*qjs.JSContext, proto: qjs.JSValue) void {
    _ = qjs.JS_SetPropertyStr(ctx, proto, "parseFromString", qjs.JS_NewCFunction(ctx, js_parseFromString, "parseFromString", 1));
}

pub fn installEventBindings(ctx: ?*qjs.JSContext, proto: qjs.JSValue) void {
    {
        const atom = qjs.JS_NewAtom(ctx, "type");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_type, "get_type", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "bubbles");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_bubbles, "get_bubbles", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "target");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_target, "get_target", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    {
        const atom = qjs.JS_NewAtom(ctx, "currentTarget");
        const get_fn = qjs.JS_NewCFunction2(ctx, js_get_currentTarget, "get_currentTarget", 0, qjs.JS_CFUNC_generic, 0);
        const set_fn = w.UNDEFINED;
        _ = qjs.JS_DefinePropertyGetSet(ctx, proto, atom, get_fn, set_fn, qjs.JS_PROP_CONFIGURABLE | qjs.JS_PROP_ENUMERABLE);
        qjs.JS_FreeAtom(ctx, atom);
    }
    _ = qjs.JS_SetPropertyStr(ctx, proto, "stopPropagation", qjs.JS_NewCFunction(ctx, js_stopPropagation, "stopPropagation", 0));
    _ = qjs.JS_SetPropertyStr(ctx, proto, "preventDefault", qjs.JS_NewCFunction(ctx, js_preventDefault, "preventDefault", 0));
}
